### ISSUE TITLE
I broke the game when shift clicking items

### ISSUE THREAD

**Issue by tyler489** [MyM-ModpackTeam/hypovolemia#100]
https://gist.github.com/Slind14/c5125ccaeefdc2b0b689

**Comment by Slind14** [comment]
Is this the complete report? It looks like there is something missing at the top.

**Comment by tyler489** [comment]
oops it got cut off hold on

**Comment by tyler489** [comment]
Also 100 Bugs Congrats @drz2k

**Comment by Slind14** [comment]
yeah, hopefully solveable with a nei and nei addon's update

**Comment by tyler489** [comment]
Closing for now..

**Comment by tyler489** [comment]
(
