### ISSUE TITLE
Wacky wolves

### ISSUE THREAD

**Issue by TheLogan** [MyM-ModpackTeam/hypovolemia#103]
I just had a weird thing happen, though this is probably related to the mod they are from and not to hypovolomia.
Two wolves came at me in the early morning hours growling and eyes shining red, and then they just stood there growling, but not attacking, I walked around and they sort of "blinked" around me, it was very weird, then the sun rose and they blinked out of existence.

**Comment by tyler489** [comment]
The wolves are agrowolves there suppost to be red eye and growl
It is possible to tame them (sometimes(bug?))and they despawn when the sun rises when tamed.

**Comment by TheLogan** [comment]
Red eye and growl sure, but I expected they would attack me?
The blinking (teleporting) around however I'm certain that can't be on purpose

**Comment by tyler489** [comment]
if you are weaking diamond or higher amor they do no damage... the teleporting behavior I can only explain if they were taimed.

**Comment by tyler489** [comment]
@pizzaluc its your mod...

**Comment by TheLogan** [comment]
Oh, I'm wearing crucio armour, so that may be why, still it's weird that it doesn't even feel like they try to attack.
That said, I'm on SP and I've never attempted to to tame a wolf.

**Comment by pizzaluc** [comment]
Do crucio armor have some special features of any kind or is it just normal damage reduction?

**Comment by TheLogan** [comment]
To my knowledge it doesn't have anything apart from damage reduction. (88%)
And in fact I'm wearing an UNarmoured jetpack instead of the chestplate, so I should have taken damage there.

**Comment by TheLogan** [comment]
I just met some in the midst of night and they instantly attacked and harmed me as was expected. So whatever the cause, it seems like it was a one off.

**Comment by drz2k** [comment]
Ill point pizza to this issue but i think i can close it ;)

If not, just comment on it.
