### ISSUE TITLE
Boggling Goggles

### ISSUE THREAD

**Issue by TheLogan** [MyM-ModpackTeam/hypovolemia#104]
Yet another quest bug, this time recipetorial in nature.
The quest Goggles, again in Thaumcraft, calls for a pair of "Goggles of Revealing"

Now, the quest text just says
"...transform two of those Thaumometers into goggles."

Well, NEI doesn't contain a recipe, and "transform" isn't a very helpful description =P

**Comment by tyler489** [comment]
Read the Thauminomicon you must reserch  first...

**Comment by TheLogan** [comment]
Oh, derp. Considering how many times I've played Thaumcraft, I'm ashamed to have forgotten that xD

**Comment by tyler489** [comment]
I did the sam with the golden wand..

**Comment by tyler489** [comment]
can you close this

**Comment by TheLogan** [comment]
I have no idea how to

**Comment by tyler489** [comment]
at the bottom it should say close in red by the comment box

**Comment by Slind14** [comment]
Would it be worth of making this more clear?

**Comment by TheLogan** [comment]
I think it would yes, it seems to me that for someone who has never done Thuamcraft, the idea that things need to be researched would be completely foreign and wouldn't cross their mind at this point, even someone like me who has done thaumcraft since like thaumcraft 2, can overlook it.
I'd perhaps consider making it a 2 parter, so part 1, you need the actual unresearched research note, and step 2 you need the goggles. 

The danger however could be I imagine is if you get the research note, you research the goggles and you forgot to actually open the HQM book, so you can't complete the quest, but if there's a sure fire way of doing it, that's what I'd do.

**Comment by drz2k** [comment]
Research notes? We will add a lorepage for TC that points to the nomnomnicon.
