### ISSUE TITLE
Invincible villagers

### ISSUE THREAD

**Issue by chuggafan** [MyM-ModpackTeam/hypovolemia#107]
Sometimes villagers can be invincible, haven't tested with other mobs yet but @drz2k can confirm this

**Comment by Ferrettomato** [comment]
As a witness, I can confirm this as well. It took several beatings from a staff of power.

**Comment by Slind14** [comment]
confirmed on sp or mp?

**Comment by chuggafan** [comment]
MP, haven't tried SP

**Comment by Slind14** [comment]
@Ferrettomato mp for you too?

**Comment by chuggafan** [comment]
Slind, i was the one to show him this on MP, so afaik he only has seen it on MP

**Comment by SirWilli** [comment]
I think that is the same issue which happens sometimes with spiders on other packs on the server too.

**Comment by tyler489** [comment]
I wanted some clairication for this so I toke 2 maxed draconic villaer spawerners in a new sp world and let them run for an hr after my frames droped I used a sop and not one of them lived.

**Comment by profrags** [comment]
Is this not caused by technomancy's 'treasures' config option?

**Comment by johnfg12** [comment]
is it?

**Comment by chuggafan** [comment]
It's server side only, so it's server related

**Comment by chuggafan** [comment]
this should have been closed nearly a year ago
