### ISSUE TITLE
The alchemy table sometimes crashes you when looking up it's uses

### ISSUE THREAD

**Issue by chuggafan** [MyM-ModpackTeam/hypovolemia#108]
Title describes it all, here's the report: http://pastebin.com/qAced7L2 Accidentally posted the wrong report, but still something to report, sorry

**Comment by shaggy1395** [comment]
Confirmed on my side.  I first noticed it when I went to look up uses for the Spider Eye, which crashes the game every time.  I noticed the WayOfTime recipe handler in the crash log so I started looking up recipes for the altar without any problems.  I moved onto the alchemy and found it crashes every time.

To reproduce, look up any item that has a blood magic alchemy recipe, then click the LP cost number to display all alchemy recipes, the game will then crash.

Log:  http://pastebin.com/aLVqWRQD

**Comment by shaggy1395** [comment]
Along with the Spider Eye, the Poison Potato is also a guaranteed crash when looking up the uses in NEI.

**Comment by drz2k** [comment]
Should be fixed with new BM version.

**Comment by shaggy1395** [comment]
Great to hear!  Do you know when the new version will make it into the pack for testing?

**Comment by chuggafan** [comment]
should be soon, the pushes take awhile to happen ;)

**Comment by drz2k** [comment]
0.0.17 is live since ~8h

**Comment by chuggafan** [comment]
shhhh, i just got home lol

**Comment by shaggy1395** [comment]
Aw heck, I've been playing longer than that.  Thanks.
