### ISSUE TITLE
Crashing when looking up melifulous hunger uses

### ISSUE THREAD

**Issue by chuggafan** [MyM-ModpackTeam/hypovolemia#109]
Title describes it all here's the correct crash report for this issue http://pastebin.com/UwAi4Mgf (my other thread explains the wording ;) )

**Comment by Slind14** [comment]
graphic card driver up to date?

**Comment by chuggafan** [comment]
No, but haven't had the time to update it, wasn't happening before this update is the thing though

**Comment by chuggafan** [comment]
Also, other people have experienced this crash @drz2k is someone else who did

**Comment by tyler489** [comment]
That crash report :HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw
Lol gg mojang

**Comment by chuggafan** [comment]
I didn't even notice that, LOL

**Comment by drz2k** [comment]
Should be fixed with new BM version.
