### ISSUE TITLE
Thaumcraft crucible duplicates buckets

### ISSUE THREAD

**Issue by shadowpanther** [MyM-ModpackTeam/hypovolemia#115]
Try to fill an empty Thaumcraft crucible with a bucket of water.
Apart from a crucible getting filled, you'll get your original bucket empty (as expected), another empty bucket in inventory and a source block of water on top of crucible.

**Comment by chuggafan** [comment]
Known bug always, probs been brought to azanor multiple times, but he won't fix as he's moved on to the next version of minecraft

**Comment by drz2k** [comment]
Wow this bug is old. And Azanor so active wow.

Theres a bucketfix.jar floating around but I cant see where its from and the license on it, so cant put it in :(
