### ISSUE TITLE
No way to get Crystal Clusters for T6 altar

### ISSUE THREAD

**Issue by shadowpanther** [MyM-ModpackTeam/hypovolemia#117]
To make Crystal Cluster (apart from killing a ridiculous number of Withers), you need a bunch of Attuned Stones.
Whiff of Magic for those could be made:
- in Witches Oven from Rowan Sapling, which is not attainable without progress in Witchery quest line (I suppose, as I don't see further quests), which is broken because Belladonna seeds are not being detected.
- in Distillery, which needs an Attuned Stone (see above) to make.

**Comment by Bennyboy1695** [comment]
Fixed in 0e03a7cde7a3ab7f97beeaeee0ae12c6bf70dd39

**Comment by tyler489** [comment]
rowan saplings can be found with loomium flower munthndus like I got mine from

**Comment by tyler489** [comment]
Mutandis
