### ISSUE TITLE
Quest idea: Blood Letter's Pack

### ISSUE THREAD

**Issue by shadowpanther** [MyM-ModpackTeam/hypovolemia#118]
Until you get pumps to automate pumping blood into the altar, standing and pr*cking (Richarding) yourself with a knife gets boring after a while. Fear not, gods offer you a way to Richard yourself without Richarding yourself. Just wear this vest on your chest, and it'll pump your blood directly from your beating heart. You can go around doing your chores, and when you return to the altar, just empty the vest into it and please the gods with yet another sacrifice.

(a quest for chapter 1, somewhere near the water bucket and chemistry set - to make leather)

**Comment by drz2k** [comment]
Accepted but done different :)
