### ISSUE TITLE
Suggestion:  Lower early game blood requirements

### ISSUE THREAD

**Issue by shaggy1395** [MyM-ModpackTeam/hypovolemia#119]
I've recently started this pack coming in with minimal knowledge of blood magic.  I was excited to find no Ex Nihilo in this pack, no more sifting for days!  However, once I got started, I found the blood requirements fine at first, then quickly turned into a long haul process.  So, I did some math.

To get a single stack of cobblestone, which is a basic material we need for a ton of tasks, requires the following:

First, gather 64 skulls.  Not too difficult considering the bone "trees" in the world.  Next, process in the blood altar:

Skull > Dirt = 100 LP each
Dirt > Gravel = 200 LP each
Gravel > Sand = 200 LP each
Sand > Cobble = 200 LP each
44800 LP total for the stack

The blood altar processes at roughly 1 second per 20 LP.  This is 2240 seconds or 37.33 minutes.  And that's assuming you have optimal incoming blood flow and an automation method such as a hopper or altar diviner.  I lucked out in my first test world by starting next to a huge blood ocean, however my next world started me in a massive barren area with no more than a couple small blood puddles.  I could see this being a big concern for a player that would have to stand there stabbing themselves endlessly to produce enough blood, and having to wait for regen in between.

Granted, I know there are speed increases you can add to the altar later.  But that is much later.  There is also the option of getting earth seeds to 10/10/10 to cut out the skull-to-dirt conversion.  Then quite a bit later is the fire seed option to cut out the conversion process all together.  In the meantime, it's a pretty heavy time sink for a player just getting into the pack.

I would personally recommend at least half the LP requirements for the Skull > Dirt > Gravel > Sand > Cobble > conversion chain.  I can see a good reason for leaving the Netherrack and End Stone values higher though.

**Comment by drz2k** [comment]
Why would you make stacks of cobble before advancing in the questline far enough to have tanks/pumps?

**Comment by chuggafan** [comment]
^^^ it isn't even possible in normal blood magic to make stacks of the stone slates early on, this isn't something so much as needed to adress as it's a small progression lock

**Comment by shaggy1395** [comment]
I have tanks and a steady flow of blood to the altar.  The slow point is that the altar doesn't process any faster than 20 LP per second, so a stack of cobble takes 37.33 minutes regardless of how much blood you throw at it.

The only options to reduce speed are the earth seeds to cut out the skull > dirt transition which cuts off 5.33 minutes, and the fire seeds much later which obviously cut out the whole process but also introduce a different waiting period.

**Comment by shaggy1395** [comment]
I'm not talking about stacks of stone slates.  I'm talking about the only way to get cobblestone which is required for numerous other things than stone slates.

**Comment by chuggafan** [comment]
uhhhhh, lava and water, DONE lol

**Comment by drz2k** [comment]
Make multiple altars?

Slates probably beeing the main use. Well go into magical crops or make a cobblegen either vanilla or ae2 automated.

Bah chugga beat me :D

**Comment by chuggafan** [comment]
lol, btw, just saying, the ofanix was so awesome for that, thx caithleen for removing it D:

**Comment by shaggy1395** [comment]
I've been doing modded MC for so long I hardly remember how to make a vanilla cobblegen.  But, if the answer is "bypass the core mechanic of the modpack entirely" then so be it.

**Comment by chuggafan** [comment]
it's completely intended for the lava/water trick to work, not hard lol

**Comment by drz2k** [comment]
How is it bypassing? If i dont block it, its probably intended. In fact i want the player to have an ae2 cobblegen later.

Many of the initial bm recipes are for starting you off. Some will stay like the wooden splinters, others will be replaced with more comfortable means to get the stuff, like magical crops.

And dont ask me how to get glowstone please xD

**Comment by shaggy1395** [comment]
I guess coming from an oblivious noob perspective, which it seems I'm doing unintentionally, I see a modpack intended to use blood for all of the things and I just keep thinking of ways to make the blood do what I want.  I'll try to go back to non-blood ways of thinking.

**Comment by shaggy1395** [comment]
And just because I forgot to mention it, the stack of cobble was for the Tier 2 altar, since you need 64 stone to make the 8 runes.
