### ISSUE TITLE
Mod bug?  Lore expansion audio replays often

### ISSUE THREAD

**Issue by shaggy1395** [MyM-ModpackTeam/hypovolemia#120]
After audio from the lore expansion plays, it will replay the last 1-2 seconds of audio every time you escape to the menu then return to the game.

**Comment by Zarvoxbe** [comment]
I think it's a lore expansion bug because I've encountered this in other modpacks.

**Comment by SirWilli** [comment]
Still? I can't reproduce it. If I play a lore and press esc, then close the menu again it just continues the lore.

**Comment by drz2k** [comment]
Cant reproduce either. Someone else can do?

**Comment by shaggy1395** [comment]
Still happening, here are the scenarios I can reproduce every time:

1. Begin playing lore audio, then pause the audio.  Close the book, escape to menu, return to game, audio resumes automatically instead of remaining paused.  This does not happen if you stop the audio instead of pausing.

2. Play lore audio to completion, notice the play button is still active with the pause option.  Close book, escape to menu, escape back to game, audio re-plays the last second or two of audio.  This will repeat every time you escape to the menu and return to the game.

Agreed, it's a minor issue, but still an issue nonetheless.  The issue does not happen if audio has not played during the game session, or if you manually stop the audio.

**Comment by johnfg12** [comment]
is this still a issue?

**Comment by johnfg12** [comment]
ive tested on the latest version and it doesnt seem to be a problem anymore
