### ISSUE TITLE
Mod bug?  Tier 2 altar with only 10k LP storage

### ISSUE THREAD

**Issue by shaggy1395** [MyM-ModpackTeam/hypovolemia#121]
After I built my Tier 2 altar, I mistakenly broke one of the runes thinking I could move it.  After building a replacement rune and placed it down, my altar changed back to a Tier 2 once more.  However, the capacity stayed at 10k instead of the expected 16k.  It shows this way in Waila as well as when using the divination sigil.  I was still able to craft my apprentice blood orb by manually filling the altar as it drained to get the required 12k LP.

Screenshot:  http://i.imgur.com/pp318Py.png

I'm about to build another Tier 2 to test.

**Comment by drz2k** [comment]
Even your t6 altar will only have 10k lp if you dont add capacity runes ... vanilla bm behaviour.
