### ISSUE TITLE
Quest "Crucio" detects Crucio without crucio

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/hypovolemia#122]
As soon as I had crafted the Accio to finish quest "Accio", quest "crucio" detects crucio without crafting it.

**Comment by drz2k** [comment]
Tried several times to reproduce this. Cant. Are you sure you didnt had one Crucio allready made via the Alchemy set?

**Comment by Sandstroem** [comment]
I am quite sure that I did the Accio quest as soon as I was able to, so at this point I couldnt have been able to get the crucio, since it needs a higher tier of orb, right?

I am quite sure that there was no crucio in my inventory. Unless there is a bug in the orb-requirements to make it and I oversaw it.

**Comment by Sandstroem** [comment]
I had a questbook reset due to my namechange. I will try to see whether I can reproduce this somehow.
