### ISSUE TITLE
Wooden Water Tank crash

### ISSUE THREAD

**Issue by chikinnuggit** [MyM-ModpackTeam/hypovolemia#124]
Wooden water tanks crash when placing 2 or more next to each other, when I reconnect I still have the item, and it's placed, but the tanks do not connect.

**Comment by Bennyboy1695** [comment]
Please include your crash report using https://gist.github.com/ if your not sure how to obtain the report follow the link located at http://mym.li/crash

**Comment by Sandstroem** [comment]
Please note that the spawn of ghasts seems to be related to the lava in some yet to determine way.

**Comment by chikinnuggit** [comment]
I didn't have a crash report because I was on the server, But I recreated it in singleplayer.
<script src="https://gist.github.com/chikinnuggit/b24859fee1458b96ab75.js"></script>

**Comment by Bennyboy1695** [comment]
is it any water tank or just a specific one ?

**Comment by chikinnuggit** [comment]
It happened to me with an oak tank from agricraft.

**Comment by tyler489** [comment]
update agricraft  to 1.4.3 they have new multiblock fixes
InfinityRaider/AgriCraft#452

**Comment by tyler489** [comment]
<mod issue>

**Comment by tyler489** [comment]
mod issue

**Comment by drz2k** [comment]
https://github.com/MyM-ModpackTeam/hypovolemia/commit/4d03233128ecaacfd64bb3aa0cbff686720bdacd
