### ISSUE TITLE
Suggestion: Armourer's Workshop

### ISSUE THREAD

**Issue by inhumanefox** [MyM-ModpackTeam/hypovolemia#126]
This mod is already included in Galactic Science,  but I believe it is so awesome it should be included here too. It adds to the immersion as some vanity armors can be done to resemble something blood-related.

**Comment by chuggafan** [comment]
Because it's included in gs =/= it will be in here, and last i checked armorers workshop is known for crashing

**Comment by drz2k** [comment]
Its deep down on the optional list already...

aka

... when beta client is done and i cant add it without performance issues or crashes, its in. Else it lost ;)
