### ISSUE TITLE
Suggestion: Thaumic Horizons

### ISSUE THREAD

**Issue by inhumanefox** [MyM-ModpackTeam/hypovolemia#127]
First off, I want to say that this mod is what I believe a great addition to the modpack, and it deserves a full and detailed explanation,  but I dont want to make this thread very long.
Thaumic Horizons consists of four (almost 5) main uses that are unique and fun, and would make some of the ways of getting materials so much better.
I will explain each of the uses briefly, if you want a more detailed explanation,  you can just ask me and I can enlighten you on this great mod.
1. Golem animation. It lets you use powder/wand focus to animate almost every block (even modded) into a golem.
2. Human augmentation. It lets you feed yourself, heal yourself and even create a superhuman clone with several upgrades.
3. Cloning and creating mobs. It allows you to gather DNA from mobs to make clones or create villagers, animals and other mobs.
4. Syringe potion effects. It allows you to infuse blood syringes with custom potion effects and inject them into either yourself or others.
5. WIP Vortex dimention. This is a storage dimension and crafting system somewhat similar to the alfheim portal. 
Because it is a thaumcraft addon, it also contains many other single items not completely related to the main theme, such as an amulet that makes all of your inventory drop elsewhere, an indestructible boat, an upgrade to the goggles (night vision, xray, scanner), and much more.
This will absolutely help creating villagers, removing the need for animal seeds.
Please dont hesitate to ask questions.

**Comment by chuggafan** [comment]
Villagers are easy to create, golem animation is done well by thaumcraft, the augmentation isn't really needed, cloning mobs can be done by other means, potion effects use actual potions, it's unnecessary

**Comment by drz2k** [comment]
Needs more opinions

**Comment by tyler489** [comment]
I like this mod.

**Comment by Bennyboy1695** [comment]
I think caith wants more reasons why to add it not just "i like this mod" :stuck_out_tongue:

**Comment by inhumanefox** [comment]
Well, I have been thinking on why should this be added, and I think that it could replace animal seeds. You see, it has this multiblock structure called the vat, which works pretty much as an incubator. One of the quest rewards could be a syringe containing animal blood, and then you can easily reproduce any animal from this blood syringe. this can be done with pretty much anything, and even vanilla animal breeding could be disabled to force you to use this vat for animals.

**Comment by shaggy1395** [comment]
Honestly it would be nice to see a more unique method of animal farming/duplication.  It would be a nice departure from regrowth's "grow everything from seeds" method that so far seems to continue in this pack.  Granted I haven't seen the later quest lines yet so there's likely something I'm not seeing for that yet.

I'm not sure the golem animation is necessary, since it seems to be cosmetic only.

The syringe potion effects is certainly thematic, but what does it do other than an alternate method of applying potions?

**Comment by inhumanefox** [comment]
1. Thats exactly what I am trying to avoid,  as it becomes repetitive, cheaty and boring (maybe just for me) to grow animal and mob drops.
2. Some golems actually have different stats depending on the material, similar to how ProjectE checks for EMC on crafted materials. (Nether star block from FM, Terrasteel or elementium)
3. Potions are made from essentia and your blood, and must be crafted balancing pros and cons, as several essentia vis have both positive and negative effects. 
It also includes custom potion effects, and don't forget human upgrades. There is lots to do, please check the documentation for more info, or just ask me.

**Comment by drz2k** [comment]
Im still not hooked.

1. I dont like the picture of happy animals in the afterlive world. It wont fit.

Im with you on the "grow everything is boring" thoo.

2. I dont think that golem will be a mayor thing in this pack.

3. I have no insight in those potions, so maybe some expamples. We already have alot of BM potions and even most of them are useless quite fast.

**Comment by drz2k** [comment]
It saves 1. 2. 3. as 1. 1. 2. -.- when i edit it, it goes back to 1.2.3. ... hate you github

**Comment by Slind14** [comment]
markdown, fixed it by breaking the syntax
