### ISSUE TITLE
Change Recipe for first Tinkers Book

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/hypovolemia#128]
I wanted to look something up in the Tinkers Books, but they are not craftable. The first needs a blank stencil from Tinkers. I suggest changing that recipe, so that it uses one of the mold patterns (the raw or cooked on) from Foundry. (I am not in game, so I don't have the correct item names here)

**Comment by shadowpanther** [comment]
But we don't use Tinkers at all, why would you need the book?

**Comment by Sandstroem** [comment]
You can still craft certain Tinkers Tools, by getting the parts with Foundry and the Alchemy Thing from Bloodmagic. I wanted to look up something on the metals. You can also put Modifiers on them.

I crafted myself yesterday a Full-Cobalt Hatchet with Beheading 3 for example.

**Comment by drz2k** [comment]
well ... why not
