### ISSUE TITLE
More usage of metals

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/hypovolemia#129]
I have reached Tier 5 altar and I am working on the Tier 5 Orb. So far Tin, Aluminium and Copper have been more or less useless, but I am starting to hoard on them, just by manually harvesting the berries now and then. I suggest to introduce some use for them or get rid of them completely.

So far they are just metals more or less filling up unneeded. Unless you want to build a house out of Tin blocks.

**Comment by drz2k** [comment]
https://github.com/MyM-ModpackTeam/hypovolemia/issues/85

Its in the works ;)

**Comment by tyler489** [comment]
a generator that burns ingots???
