### ISSUE TITLE
Suggestion: Introduce Gendustry with heavily modifed Forestry

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/hypovolemia#130]
Hi, 

I am not sure whether that works.I have been playing some bee related pack lately, and I really liked Gendustry. So I was wondering whether it might be possible to include Gendustry. It needs Forestry, which I don't really want, but maybe traditional Bee Breeding could be disabled somehow?

I think introducing Gendustry without Forestry might be some unique thing todo, and the whole Genetics thing fits a bit to the blood theme. I had quite fun fiddling around with the genetic samples and stuff.

Maybe you could even disable some seeds, and the player has to get the bees to produce this special resource, so this is not just a mod that people avoid.

**Comment by shaggy1395** [comment]
I absolutely love Gendustry's implementation of bee genetics.  I have seen a bit about Binnie's new version as well and it looks promising.  I agree that the genetics does match with the blood theme, as well as the more advanced tech themes later.  Binnie's also adds a ton of extra bees that could be used as a replacement for some of the crop methods.  And of course Magic bees is another that adds more bees which work into the magical component of the mod.

That being said, there would need to be a way to remove the hives from spawning in the world, and then a way to acquire princesses.  I know Ex Nihilo adds the artificial hive that can attract princesses, but I'm sure there's a better way that doesn't involve adding the "sift everything" mod into the pack.

**Comment by Sandstroem** [comment]
Getting princesses would be easy. You could use the Alchemy Set to "copy" princesses (only the hive ones of course), like you can do with the Demonic Shards for example.

For getting the different princesses, maybe add a botania or bloodmagic recipe which just circles through a number of princesses.
The start would be just a number of princesses and drones you get somewhere down the line as a reward.

As soon as you have taken the type sample of one hive bee, you can apply it to one spare bee and then copy this one like described above. You would get a "default" bee of the same type.

Just some ideas how this mechanics might work. Of course I don't know whether that can be implemented this way.
Some items like the lab ware or the clean samples might only be crafted in a unsterilized way and have to be sterilized/purified with blood or maybe mana.

I have to look into Binnies mods yet.
What I rather would not like to see though is a ton of new wood types, that is why I like to keep this down to bees and Gendustry.

**Comment by drz2k** [comment]
Humm, bees in the afterlife. Dunno. Maybe really heavily tweaked. More opinions?
