### ISSUE TITLE
Suggestion: add advanced solar generators from mekanism back in

### ISSUE THREAD

**Issue by chuggafan** [MyM-ModpackTeam/hypovolemia#133]
The reason for this is so that people can make the Solar evaporation plant, a device needed to make brine, which is used to make salt, which is needed for ore quintupling, it is also hinted at multiple times to get hydrogen chlorine in the questlines, of which you can't get without a source of brine, and since atm that source of brine is limited, your source of hydrogen chlorine is also limited

**Comment by tyler489** [comment]
I was told they wernt disabled by caithleen when I started building our plant.

#61

**Comment by chuggafan** [comment]
? that doesn't say anything about caith not disabling them, and afaik you can't make brine any other way, as i was poking around in NEI, as the solar evaporation tower is the ONLY thing able to make brine, at all, doesn't matter if liquified

**Comment by tyler489** [comment]
ikr I asked caithleen ingame and was told he hadnt disabled them

**Comment by drz2k** [comment]
Solar power from mekanism?

I usually have a hard time to decide on suggesstions, but this one is easy ;)

Denied :D

**Comment by chuggafan** [comment]
there's an alternate? can't find it at all, do tell, please

**Comment by tyler489** [comment]
yes please do as I couldnt find it eaither.
