### ISSUE TITLE
Charged Iron wand recipe overridden

### ISSUE THREAD

**Issue by Bigmanvegas** [MyM-ModpackTeam/hypovolemia#134]
The charged 25 each vis iron wand recipe does not work in the arcane worktable as the standard shaped recipe overrides it.

Suggestion would to make either the recipe vertical/horizontal or change the stick to something else.

**Comment by SirWilli** [comment]
Hm, that are the default recipes and I don't think it is intended to get a charged wand

**Comment by Bigmanvegas** [comment]
Just making sure it is listed in NEI for a charged wand for the cost of 1 of each vis. It would make
sense as a bogo kind of deal to start out, but I didn't know if that was intended or not.

**Comment by drz2k** [comment]
Crafting filled wands is not intended. Maybe we can hide them from NEI.

**Comment by drz2k** [comment]
Pending to closure T-3
