### ISSUE TITLE
Lithium obtainable

### ISSUE THREAD

**Issue by Bigmanvegas** [MyM-ModpackTeam/hypovolemia#136]
Liquid lithium is made in the solar evaporation plant which is able to be formed without advanced solar panels then crystallized. You need lithium dust for the energized wand core and eldritch consumer.

**Comment by chuggafan** [comment]
What? how do you make the evap plant work without the solar panels? and we're trying to figure out how to make the evap plant work, as the solar panels aren't meant to be disabled

**Comment by Bigmanvegas** [comment]
Sorry it is "not able to be formed..." well technically it "does" form without the panels but it has a multiplier of x0.0 so you can fill it with water, but it won't do anything.

**Comment by drz2k** [comment]
Apart from the evap plant - Isnt Lithium only good for the reactor, which isnt in mekanism v7 ?

**Comment by Bigmanvegas** [comment]
You need lithium dust for the energized wand core and eldritch consumer in technomancy.

**Comment by drz2k** [comment]
Valid points, ill make a custom recipe for them
