### ISSUE TITLE
Dreamworld unplayable

### ISSUE THREAD

**Issue by Bigmanvegas** [MyM-ModpackTeam/hypovolemia#137]
The dreamworld is unplayable dream or nightmare due to no bone pillars spawning and no ore or ore bushes spawning.

**Comment by chuggafan** [comment]
This does not matter, dreamworld is far enough you should be able to make a travellers belt + enderchest and place an enderchest down in the spirit world

**Comment by Bigmanvegas** [comment]
Ah ha I see. I didn't try the traveller's belt just the knapsack and found out that was made "dimensionally aware" so you couldn't use it in the dream world.
