### ISSUE TITLE
[Bug] Crash When Opening

### ISSUE THREAD

**Issue by beach-boy98** [MyM-ModpackTeam/hypovolemia#139]
When I load up the game using the Mine Your Mind client I get so far then a crash. I have the latest pack and java x64 installed. I am running windows 10 Home. It worked fine on 8.1. 

It also happens of the FTB launcher.

**Comment by chuggafan** [comment]
Crash-report required to give any more help

**Comment by tyler489** [comment]
can we get the launcher log.
try this right click the mym launcher. if you see somthing about compatability click there and run it in compatability with windows 8 if you dont see a compatability click propertys then compability.

**Comment by beach-boy98** [comment]
http://pastebin.com/J1v0GWYe this is what it says in the console.

http://pastebin.com/2kZcY38i Crash Report. 

Running in compatibility mode has no eeffect

**Comment by Slind14** [comment]
Two things. 
1. get your graphic cards driver up to date if it isn't
2. reinstall the modpack (right click, hard-force update)

**Comment by beach-boy98** [comment]
Both have been done several times.

**Comment by SirWilli** [comment]
Also try to reinstall java

**Comment by beach-boy98** [comment]
I have tried both 32/64 bit and they have no effect.

**Comment by Sharkman9000** [comment]
im having this problem too

**Comment by chuggafan** [comment]
Shark we'd also need your crash-report, incase it's a different problem...

**Comment by drz2k** [comment]
http://hopper.minecraft.net/help/pixel-format-not-accelerated/

See this KB from mojang and follow the instructions.

**Comment by beach-boy98** [comment]
I have sorted it I just had to use an older Java version.
