### ISSUE TITLE
Blood alter bug

### ISSUE THREAD

**Issue by Sharkman9000** [MyM-ModpackTeam/hypovolemia#141]
When i fill my blood alter its always draining 
![2015-11-22_10 50 18](https://cloud.githubusercontent.com/assets/15968939/11325026/77146f34-9108-11e5-980c-ebbc3d142631.png)
![2015-11-22_10 50 31](https://cloud.githubusercontent.com/assets/15968939/11325027/7a483960-9108-11e5-85c0-fbb09424dd1a.png)
![2015-11-22_10 52 16](https://cloud.githubusercontent.com/assets/15968939/11325028/7dba56dc-9108-11e5-94ba-3cd349a241de.png)

I would be delighted if someone could help me fix this so i can play with my brother

**Comment by tyler489** [comment]
its suppodt to alters have a internal buffer once it fills it stops draining

**Comment by tyler489** [comment]
https://m.reddit.com/r/feedthebeast/comments/23iou0/blood_magic_why_does_my_altar_sometimes_drain_on/

**Comment by tyler489** [comment]
or http://m.ftbwiki.org/Blood_Altar#Fluid_Transfer

**Comment by tyler489** [comment]
@chuggafan confirmation please

**Comment by chuggafan** [comment]
I have no clue what is going on exactly

**Comment by tyler489** [comment]
if you feed it 2k lp does it stop consuming as I cant reproduce this

**Comment by chuggafan** [comment]
Can't test on server, i'm too lazy to setup singleplayer for testing atm, can someone else confirm/deny this?

**Comment by drz2k** [comment]
Its always been like this (not very intuitive thoo). Internal tanks fill first. You can use a sigil of sight to check this.
