### ISSUE TITLE
200+ levels from killing a mounted spider

### ISSUE THREAD

**Issue by smisch** [MyM-ModpackTeam/hypovolemia#142]
Hey,

I just killed a spider mounted by a creeper with a non-enchanted bound sword. The spider died with 2 hits and upon death gave me a short regen buff and an extreme amount of exp. I'm currently at level 200 (up from lvl <10) and the exp is still not used up. 

Maybe this is somehow related to Draconic Evolution. From what I understand killing an ender dragon will also give a regen buff and much exp. 

I really enjoyed your pack so far, btw. :-)

**Comment by chuggafan** [comment]
what? this needs further testing, and this is WEIRD, never experenced this before, SP or MP, further testing required ext ext

**Comment by smisch** [comment]
It was in SP. I'm not sure how I'd reproduce the issue besides trying to spawn a creeper riding a spider and killing it.

**Comment by chuggafan** [comment]
Can someone else reproduce a similar bug then?

**Comment by drz2k** [comment]
Hum, seems this hasent been reproduced or reported again. Closing.
