### ISSUE TITLE
I cant create a new world: I still need help!

### ISSUE THREAD

**Issue by kurisu-tofa** [MyM-ModpackTeam/hypovolemia#144]
None  of that other stuff worked.. so yah

**Comment by Bennyboy1695** [comment]
a bit more of a description helps ;)

**Comment by Bennyboy1695** [comment]
Reference #132

**Comment by kurisu-tofa** [comment]
link to the error
http://pastebin.com/L76jmfZC

**Comment by kurisu-tofa** [comment]
why u add duplicate to this. the other one they closed when i still need help..

**Comment by chuggafan** [comment]
hard force update the modpack, should work, no idea why it wouldn't

**Comment by kurisu-tofa** [comment]
Nope that dies nothing

**Comment by drz2k** [comment]
[17:58:29] [Server thread/ERROR] [FML]: Caught exception from BiomeTweaker
java.io.IOException: Access is denied
        at java.io.WinNTFileSystem.createFileExclusively

Launch as admin, change filelocation to somewhere UAC isnt on hard.

**Comment by kurisu-tofa** [comment]
What does that mean/ how I do that

**Comment by kurisu-tofa** [comment]
for you know im using curse launcher but i do have the mym launcher

**Comment by chuggafan** [comment]
reboot your computer actually, that should solve it ;)

**Comment by kurisu-tofa** [comment]
? do you mean restart. im not reseting me pc for a modpack

**Comment by drz2k** [comment]
Beside a restart is not a reset you got a bunch of things to try out from different people now.

If you dont try them and keep us updated we cant help you.

**Comment by SirWilli** [comment]
Check the curse launcher settings, somewhere there you can change the modpack location probably.

**Comment by kurisu-tofa** [comment]
change the location to where though
also i wont be able to answer for like 7 hours. heading to school.

**Comment by SirWilli** [comment]
No idea somewhere where your user does have permissions

**Comment by kurisu-tofa** [comment]
My user is the only user, be full admin permissions on everything

**Comment by SirWilli** [comment]
Then no idea whats wrong with your system

**Comment by chuggafan** [comment]
@kurisu-tofa DID you REBOOT your computer? DID you turn it OFF, and ON again? basic tech support questions, i'm going to go on a strech and say another program was accessing the files.... you have any viruses? etc etc you can drill through the general tech support questions

**Comment by kurisu-tofa** [comment]
turning it off then on again does nothing also i dont have any viruses

**Comment by drz2k** [comment]
Your user may have full admin permissions, but the program you are launching hasnt as long as you are not launching it as admin as i suggested ....

**Comment by kurisu-tofa** [comment]
i launch most things with admin perms. i tryed that. it did nothing.......

**Comment by drz2k** [comment]
Well no idea then.

Anyways, this is the issuetracker of a modpack and we are already deep into a PC support case here. Closing this now.
