### ISSUE TITLE
Buggs within the quest book as of 0.0.20

### ISSUE THREAD

**Issue by miner-bob-1960** [MyM-ModpackTeam/hypovolemia#146]
Having completed 92% of the quests here is a list of all the quests that can not be completed.
- [ ] 1: Meka...meka...nism. Now Combine it, Chemical Infuser, the book dose not recognize it, tho this is only the mym server. Single player its ok
- [ ] 2: Technomancy, Creating Nodes, the node fabricator can not be crafted.
- [ ] 3: Technomancy, Essentia Quarry, book dose not recognize the Eldritch consumer.
- [ ] 4: Thaumcraft, Even Better, Thaumiun Bossed silverwood Scepter, book dose not recognize the scepter, full or empty.
- [ ] 5: Thaumcraft its been said that as of 0.0.20 iron capped wand dose not detect.
- [ ] 6: Second chance, None of the potable tank quest are doable,
- [ ] 7: Second chance, Item storage, book dose not recognize the ME 16384 Item Storage cell,
- [ ] 8: Second chance, Fluid storage, book dose not recognize the ME  4096 Fluid Storage cell.

Future problem may arise with Coven Witches, as the have a tendency of teleporting to you. This is not a problem if you fighting mobs with a normal weapon, but if you using the Draconic staff of power, with a A.O.E of 25x25, you end up killing the coven witches..

**Comment by chuggafan** [comment]
the coven witches part has an issue i made a long time ago, it's marked for beta release though, so might not be until later it is implemented

**Comment by tyler489** [comment]
2. its thaumcraft its in the thaumomonocon

**Comment by tyler489** [comment]
thats 2 not one

**Comment by tyler489** [comment]
#111

**Comment by miner-bob-1960** [comment]
2: Technomancy, Creating Nodes, the node fabricator can not be crafted.
if its this you referring to, I/we that have tried to craft it ACCORDIND to the thaumomonocaon, and the infusion will not start.

**Comment by johnfg12** [comment]
1. not our issue
2. works for me 
3. what quests thats?
4. works for me
5. works for me
6. are you using the QDS?
7. works for me although i had to click manual submit 
8. works for me although i had to click manual submit

**Comment by tyler489** [comment]
6. it used to be it would work with creative spawned tanks but not survivial filled tanks

**Comment by johnfg12** [comment]
thats a detection error then @GGothicRide can you sort 6?

**Comment by johnfg12** [comment]
should be sorted
