### ISSUE TITLE
The Near Impossible Quest

### ISSUE THREAD

**Issue by miner-bob-1960** [MyM-ModpackTeam/hypovolemia#147]
Near Impossible I say as only a mad man would try,
After completing all other quest (see #146), I turned my attention to the only quest left, the unnamed quest in Second Chance, The Blood Tank. So I enter my test world and spawn in the tanks 1 by 1 to see which 1 is required, of course it the top tier, tier 16.
So onto the Near impossibility of this quest.
To get a tier 16 Blood tank, assuming you make 1,000 blank slates per hour would take over 11 years 24/7 play time. 
The maths
Blank slates required total ((3^16)x2)+(3^15)+1=100,442,350 (86,093,442 blank slates for the tier 1 tanks, 14,348,908 for the Demonic slates to upgrade from the previous tier)
100,442,350/1,000=100,442.35 hours
100,442.35/24=4,185.1 days
4,185.1/365.25=11.5 years.

To complete this near impossible quest in 1 month of game play, you need to make 120,000 blank slates per hour.
As I say only a mad man would try.

At the time of this post I'm at tier 9 :)

**Comment by Sandstroem** [comment]
Just out of curiosity: What does the rune combination look like that you use on the altar, that produces this stuff?

**Comment by shaggy1395** [comment]
Thank you for doing the math on this.  I was about to start considering doing that on my single player and thought better of it.

**Comment by miner-bob-1960** [comment]
Just now I'm using 4 tier 3 altars, with 12 speed runes and 16 dislocation runes, and can produce around 8,000 blank states per hour, so I'm a long way off way off the 120,000/.

**Comment by Sandstroem** [comment]
So if I understand you correctly, you are producing 2000 slates per hour and per altar. 12 Speed runes increase your base production by a factor of 2.4, so the base production would be something like 830 Slates per hour.

Now, a Tier 6 altar has 184 runes. I am not going into a efficient calculation here, lets just say you use half of those for speed. Lets say 95 runes for easier calculation. That gives you a multiplication factor of 1+0.2*95, which is 20. So now we are talking about a production rate of appr.17k. Use for of those and you already reached 68k per hours, which is more than half of what you calculated.

I am sure these numbers can be optimized for more speed runes.Maybe even some more altars.
I could also see possibilities to stack multple Tier 6 Altars on top of each other and sharing runes.

**Comment by Sandstroem** [comment]
I just noticed that my calculation was a little bit off there.

12 Speed runes increase your base productivity by a factor of 3.4, not 2.4. Calculation would be 1+12*0.2 = 3.4
So your base production would be more something like 600. If I multiply this with 20 for the 95 speed runes and with 4 for the four altars, we get 48k. This is less, but doesnt really change my point in the previous post much.

**Comment by drz2k** [comment]
Humm, seems this needs some balancing :D

**Comment by drz2k** [comment]
So you guys did some math and testing on it.

Consider its one of the last hoarding quests, which blood tanks seems to fit for it ?

**Comment by GGothicRide** [comment]
is being looked into for future reference via the quest book have an idea on how to sort this issue

**Comment by johnfg12** [comment]
il close this as gothics solution has been implemented in our test branch
