### ISSUE TITLE
Iron Capped Wooden Wand does not detect in the Quest Book

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/hypovolemia#148]
As the topic says.

One user made a ticket about that, I also see it reported in the FTB forum thread and I can reproduce it myself.

**Comment by Bennyboy1695** [comment]
Ref #102 , #71 , #106

**Comment by Werwolfi** [comment]
We recently got a ticket that the quest is still bugged

timmyforchelsea:
Both the Newly Crafted 0 vis and Fully Charged 25 vis Iron Capped Wooden Wand wont work to complete the quest in thaumcraft

**Comment by profrags** [comment]
Issue is fixed in the new update that is going to be released... Soon? Hopefully.
