### ISSUE TITLE
Dieing With Sacrificial Knife Crashes Client On MP

### ISSUE THREAD

**Issue by Vifury** [MyM-ModpackTeam/hypovolemia#149]
If you kill yourself with Sacrificial Knife, it crashes the client. I am using Optifine and I asked people online if it happens to them. "BiteBoy5" said that same, but he said he doesn't use Optifine. I was watching Youtube and people who were playing LAN in SP didn't have their client crashed when doing so.
My crash reports:
[crash-2015-12-22_12.55.51-client.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/70103/crash-2015-12-22_12.55.51-client.txt)
[crash-2015-12-22_13.08.33-client.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/70104/crash-2015-12-22_13.08.33-client.txt)

**Comment by SirWilli** [comment]
https://github.com/cyanobacterium/DrCyanos_Lootable-Bodies/issues/16

**Comment by Vifury** [comment]
Also, you dupe the knife. It might be the item in your hand, but I've got my knife duped, had 1, now 3 (died twice.)

**Comment by cyanobacterium** [comment]
Try this version of Lootable Bodies:
https://github.com/cyanobacterium/DrCyanos_Lootable-Bodies/releases/download/1.3.6-backport/CyanosLootableBodies-1.7.10-backport_1.3.7.jar
