### ISSUE TITLE
Can't Create a world

### ISSUE THREAD

**Issue by LifeHckr** [MyM-ModpackTeam/hypovolemia#150]
I just downloaded the pack and when I tried creating a world it brought me back to the main menu and I can't create a world.

**Comment by drz2k** [comment]
Retry to enter that world, slower machines struggle with worldgen but usually can login to the world after several tries.

**Comment by lw03** [comment]
i am also having this issue when i try to start a world it just returns me to the main menue

**Comment by LifeHckr** [comment]
I can't create a world in general it doesnt show in world list.

**Comment by drz2k** [comment]
Logs?

**Comment by lw03** [comment]
[latest.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/74717/latest.txt)
[fml-junk-earlystartup.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/74718/fml-junk-earlystartup.txt)
[fml-client-latest.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/74719/fml-client-latest.txt)

thats all i have i tryed pastebin and it wouldnt work so i hope this does

**Comment by drz2k** [comment]
[09:16:43] [Server thread/ERROR] [FML/]: Caught exception from BiomeTweaker
java.io.IOException: Access is denied

Try to launch as admin ...

**Comment by lw03** [comment]
i have allready doesnt help

**Comment by drz2k** [comment]
Well try different launcher, different location. The problem is that your mc isnt allowed to create specific files.

**Comment by lw03** [comment]
i should have stated that i have been able to play it before so i dont see how that can be the case

**Comment by drz2k** [comment]
Try to delete the stuff in /config/biometweaker/output...

**Comment by lw03** [comment]
nope that doesnt help

**Comment by drz2k** [comment]
Well, the error message clearly points to a problem writing to your file system. I gave advices on that, if you dont want to test them, i dont see how i can be of any more help.

**Comment by lw03** [comment]
i have just done everything you said... you saying i am not willing to try is fucking rude fuck your pack ill play something else prick

**Comment by drz2k** [comment]
Closing it, since its not related to the pack and the creator started insulting ;)

**Comment by lw03** [comment]
1. im not the creator
2. you insulted me by saying i wasnt testing whatever you said when indeed i did.
