### ISSUE TITLE
Several gameplay-related bugs in v 0.0.20

### ISSUE THREAD

**Issue by TIMMO1001** [MyM-ModpackTeam/hypovolemia#151]
1. I could not remove the electric chest from mekanism using any tools. Even shift-right clicking with a configurator in wrench mode rotates the chest only.

2. The recipe for blank cast using gold block is duplicate with the soft block mold.

**Comment by chuggafan** [comment]
1. try a pickaxe if you placed the chest
2. use something else, say, a diamond, those things get really cheap, maybe an emerald, which are so easy to obtain from shedding from villagers
