### ISSUE TITLE
Sanguimancy Blood Tank Server Crash

### ISSUE THREAD

**Issue by chikinnuggit** [MyM-ModpackTeam/hypovolemia#153]
When I connect an elite mechanical pipe to a 64,000mb Sanguimancy blood tank, the server crashes.
It's on the MYM server, So I can't check the errors.
![wgxbijv](https://cloud.githubusercontent.com/assets/15735845/12008901/f83bc40a-ac23-11e5-971a-fb6298dd6df9.png)

**Comment by johnfg12** [comment]
this is a issue with mek and how it interacts with other mods

**Comment by johnfg12** [comment]
fixed on mym servers by stopping the block from being placed
