### ISSUE TITLE
Lost Connection Problem

### ISSUE THREAD

**Issue by Bakterien** [MyM-ModpackTeam/hypovolemia#158]
When I try to log in to the server. The server kicked me out and say me "[Proxy]  lost connection to server". I reinstalled the mod pack and restart Minecraft an my PC, but nothing helped.
Can you help me. I like to play this mod pack.
My name in Minecraft is Bakterien.

All the best

**Comment by Slind14** [comment]
You should be good to login. For further issues regarding the server please use the ticket system or forum.
