### ISSUE TITLE
Missing Mekanism recipes

### ISSUE THREAD

**Issue by Hypersonicx** [MyM-ModpackTeam/hypovolemia#159]
Missing Mekanism recipes
I want to complete the Questline Meka..meka...nism. But there is no way to craft these machines.
They are not shown up in NEI.

Chemical Injection Chamber
Chemical Infuser
Chemical Crystalizer
Chemical Washer
Chemical Dissolution Chamber
Chemical Oxidizer
Rotary Condensentrator
Electrolytic Separator

**Comment by chuggafan** [comment]
uhhh, I can easily craft them, i completed everything except 2 quests in that questline before, so please, try before you report

**Comment by pizzaluc** [comment]
Just confirmed they are missing from the NEI
but, you can still craft them. Just find the recipe from the wiki here: http://wiki.aidancbrady.com/wiki/Tutorials/Getting_Started

**Comment by tyler489** [comment]
Not changeable by us and mekanism has moved on to 1.8 builds

**Comment by bigbluu722** [comment]
We're able to edit the recipes via minetweaker. 
-V

**Comment by tyler489** [comment]
Caith tried that they still dont show up. They work just dont show

**Comment by bigbluu722** [comment]
Hm, will look into this further once I get home. 
-V

**Comment by Bennyboy1695** [comment]
InPureCore is what causes the machines to be hidden, you'll either need to remove the mod to fix it. Or you can add all the machines that are being hidden to be forced to show in the custom.js in the config file

**Comment by Udary** [comment]
Finding "uses" for the tank exposes these recipes, but you can't search for them directly. They are classed as "Mekanism shaped" I think

**Comment by johnfg12** [comment]
il look into it in a bit :)

**Comment by johnfg12** [comment]
or not https://github.com/aidancbrady/Mekanism/issues/2948

**Comment by kindlich** [comment]
https://github.com/MyM-ModpackTeam/hypovolemia/commit/49277eeb00ae2fe527f764ce14cd91372a24154f

Should be working now
