### ISSUE TITLE
0.2.0 Dupe Bug

### ISSUE THREAD

**Issue by DrDelius** [MyM-ModpackTeam/hypovolemia#160]
It's quick, easy, and very repeatable.

Altar Diviners can dupe an item's metadata, you can copy a full portable tank onto an empty one, use a untouched tool to copy it's durability onto a tool that's almost broken, or even full on dupe the contents of a plastic bag onto another plastic bag.

Simply have two of the same item in your hot bar, and click on the diviner with the second item. It will take the first item, but use the second item's data. Simply pull your tool/tank/bag out of the Diviner, and you'll have two of the exact same item.

Working on multiplayer, haven't tried singleplayer.

**Comment by chuggafan** [comment]
Sorry for late reply: can someone else confirm?

**Comment by MohammadxCoder** [comment]
i do it ... and it happened like DrDelius said..... version 0.2.0(0.20 As FTB Launcher say)

**Comment by johnfg12** [comment]
nothing we can do so i am closing this :)
