### ISSUE TITLE
[Quadrum] Incorrectly named texture

### ISSUE THREAD

**Issue by Zirrald** [MyM-ModpackTeam/hypovolemia#161]
src/config/Quadrum/block/bones.json:
> "name": "bones",
> "default-texture": "**bones**",

 src/config/Quadrum/block/textures/**Bones**.png 

![2016-02-05_21 26 43](https://cloud.githubusercontent.com/assets/10292519/12855434/7b957408-cc50-11e5-83ca-0ee9297dbdf1.png)

**Comment by SirWilli** [comment]
Not sure yet how to fix that, as my local repo does have the correct name but git doesn't trigger a change

**Comment by Zirrald** [comment]
Maybe rename it directly from branch?

**Comment by SirWilli** [comment]
Got it with `git mv` command
