### ISSUE TITLE
Unable to create new world

### ISSUE THREAD

**Issue by Panzerwulfen** [MyM-ModpackTeam/hypovolemia#162]
Ive downloaded version 0.0.20 via Curse, MYM, and FTB launchers. I am running both the launchers and the MC executable as administrator, yet I'm getting the same error about BiomeTweaker from all three launchers when attempting to create a new world.

Now I'm taking a guess, but based on research on similar issues in other modpacks with BiomeTweaker, I think it could be an issue in the config files for BiomeTweaker itself. I've added the files as well for review in case this may indeed by the issue.

[fml-client-latest.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/121824/fml-client-latest.txt)
[fml-junk-earlystartup.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/121826/fml-junk-earlystartup.txt)
[latest.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/121825/latest.txt)
[BiomeTweaker.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/121828/BiomeTweaker.txt)
[blood.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/121829/blood.txt)

**Comment by SirWilli** [comment]
Can you please try to manually update to the latest version of BiomeTweaker and test if this fixes your issue?

**Comment by Panzerwulfen** [comment]
Updated BiomeTweaker to 2.0.182 (latest available through the curse launcher). Issue continues, new logs below. 

[latest.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/122885/latest.txt)
[fml-client-latest.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/122886/fml-client-latest.txt)
[fml-junk-earlystartup.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/122884/fml-junk-earlystartup.txt)

**Comment by SirWilli** [comment]
Try the suggestions here: https://github.com/MyM-ModpackTeam/hypovolemia/issues/132
If it then still doesn't work you would need to ask the BiomeTweaker mod dev as we can't reproduce the issue.

**Comment by Panzerwulfen** [comment]
Seems I missed a single executable in java. Once I set that to run as administrator, the issue was resolved. Still weird that I had to do that for Hypovolemia but not Regrowth.
