### ISSUE TITLE
Problem with Aura nodes

### ISSUE THREAD

**Issue by mjvlego** [MyM-ModpackTeam/hypovolemia#163]
For thaumcraft, aura node generation in the world seems to be disabled.  This may be intended.

I've found quests that give a total of 7 aura nodes as rewards.  When you place these in the world, you get random aura nodes.  It is possible to get 7 nodes that do not have all of the 6 main aspects.  If that happens you have no way to fully charge a wand.

A solution would be to either activate aura node generation in the world, or to create a repeatable quest that gives an aura node as quest reward.

As an alternative, you can use a cardboard box to transform one random node into another random node.  This seems like a somewhat clunky way to solve the problem.

**Comment by bigbluu722** [comment]
Vis can be obtained by killing mobs and having the wand in your hotbar. 
-V

**Comment by chuggafan** [comment]
solution: silverwood wands, also, as you said, cardboard boxes also work to get hungry nodes, this allows you to make MASSIVE ones

**Comment by johnfg12** [comment]
so this is a feature?

**Comment by chuggafan** [comment]
yes, definitely a feature, impossible to get otherwise, besides, this type of "bug" is a feature, didn't you know that? ;)

**Comment by drz2k** [comment]
Nah, this is indeed intended.

Silverwood wands, mob killing, cardboard boxes and the node generator.
