### ISSUE TITLE
New World

### ISSUE THREAD

**Issue by CookieMonsterV21** [MyM-ModpackTeam/hypovolemia#165]
I can't seem to make a new world and when i launch Hypovolemia it says "Error extracting native libraries"

**Comment by chuggafan** [comment]
If the modpack launches it's fine, also: are you logging onto the server before doing this? this seems to actually allow me to make a new world for some reason, it's REALLY weird

**Comment by johnfg12** [comment]
can we have logs ect plz il take a look in a bit

**Comment by Slind14** [comment]
The world creation issues are caused by biome tweaker, the repo has the latest "improved" version but the launchers don't.

**Comment by johnfg12** [comment]
ok so this is sorted on the latest version?

**Comment by Slind14** [comment]
should be, if not, there is not much we can do from our side.

**Comment by johnfg12** [comment]
ok then il close this then :)
