### ISSUE TITLE
world glitch

### ISSUE THREAD

**Issue by Luckycharms2001** [MyM-ModpackTeam/hypovolemia#168]
whenever i try and load a world it just load the main menu instead and if i try to reinstall it, it still does the exact same thing and i can't play it at all

**Comment by Arcanuo** [comment]
Which launcher are you using? FTB?

**Comment by Luckycharms2001** [comment]
The curse launcher

**Comment by Arcanuo** [comment]
Interesting, could you try FTB or MyM for me? I'll look into the issues with Curse tonight.

**Comment by Arcanuo** [comment]
Also, mind posting specs and how much ram is dedicated? Also if you want into use curse, try a couple more times. Should resolve it.

**Comment by Luckycharms2001** [comment]
How do I find that

**Comment by Arcanuo** [comment]
In the curse settings for mc it says how much ram is dedicated, try upping it to 4gbs.

**Comment by Luckycharms2001** [comment]
its already at 4gbs

**Comment by Arcanuo** [comment]
Alright, due to the older gen this sometimes happens on older machines. If you try a few more times it should work

**Comment by Luckycharms2001** [comment]
ok wait try what keep reinstalling it or keep loading it

**Comment by Arcanuo** [comment]
Loading

**Comment by Luckycharms2001** [comment]
the world or pack

**Comment by Arcanuo** [comment]
World

**Comment by Luckycharms2001** [comment]
ok

**Comment by Luckycharms2001** [comment]
yay it works

**Comment by Luckycharms2001** [comment]
It started doing it again
