### ISSUE TITLE
Bugged quest "Activation"

### ISSUE THREAD

**Issue by Nuadeilin** [MyM-ModpackTeam/hypovolemia#171]
The Blood Magic Quest Activation won't detect my Weak Activation Crystal even if i click Manual Detect

**Comment by chuggafan** [comment]
Try an unbound weak activation crystal, should work

**Comment by Nuadeilin** [comment]
thanks worked :)

**Comment by chuggafan** [comment]
NP, found out that one during the closed alpha, no real solution

**Comment by johnfg12** [comment]
u guys good now?

**Comment by chuggafan** [comment]
yhea, you can close this

**Comment by johnfg12** [comment]
ok :)
