### ISSUE TITLE
World Deleted By Itself

### ISSUE THREAD

**Issue by Braverion** [MyM-ModpackTeam/hypovolemia#179]
I have been playing the modpack for a while now, and all of a sudden, i went back on the modpack and my main save file which i always use wasn't there. If anyone knows how to retrieve the save file that deleted, please message back!

**Comment by kindlich** [comment]
A file usually doesn't delete itself...

You could try to use an undeleter to restore the folder?
Or you could check if the savegame folder still exists and your game just didn't recognize it?

**Comment by Braverion** [comment]
It has the savegame folder but it didnt recognize it like you said, what do i do?

**Comment by kindlich** [comment]
hm...
I'm not so good at this so it might ne wrong, but you could try renaming the savegame folder...

alternatively you could try creating a new world and copy the files from your savegame into that folder, overwriting the files it originally created

**Comment by Braverion** [comment]
Nothing worked, but thanks for trying to help.

**Comment by johnfg12** [comment]
this sounds like a computer issue more than a pack issue have you ran a antimalware scan recently
