### ISSUE TITLE
Any reason why your Botania version is outdated?

### ISSUE THREAD

**Issue by Fortanono** [MyM-ModpackTeam/hypovolemia#180]
The 1.8 versions (not 1.8.8/1.8.9) are 1.7.10 as well.

**Comment by Slind14** [comment]
major mod updates usually only make it in major updates as mods in this pack are heavily customized and any new block/recipe change can break the entire progression. On top, the pack hasn't been updated in a long time as it does not have active maintainers.

**Comment by johnfg12** [comment]
i dont see any reason for this extra work we will look at this when all other current issues are ironed out and the majority of quests are done i will close this for now and i will make a trello in a sec so we know what we need to do :)
