### ISSUE TITLE
Please, PLEASE disable the OP Technomancy stuff

### ISSUE THREAD

**Issue by Fortanono** [MyM-ModpackTeam/hypovolemia#182]
I love how you use Technomancy's Blood Dynamos here, but if you're a magic mod dev, Technomancy would be your pet peeve. Please disable the mana-to-RF stuff and Essentia Fuzor, the dynamos that convert magic energy TO RF should be fine.

**Comment by johnfg12** [comment]
is there any real reason for this?

**Comment by SirStudMuffin** [comment]
The issue is that if you start removing Power generation then youll have nothing left, theres already a call for more RF gens

**Comment by johnfg12** [comment]
cant see any real reason for this

**Comment by GGothicRide** [comment]
I dont see a reason for this either

**Comment by drz2k** [comment]
And I totally see no reason since those dynamos were meant to be starting/mid tier energy production ;)

**Comment by Fortanono** [comment]
Sorry, I mean the RF-to-Mana, not Mana-to-RF. Same with Essentia and Vis and Life (though the latter may be different because, y'know, blood lakes). Although, it isn't really needed even then.
