### ISSUE TITLE
Coffin and NEI issue

### ISSUE THREAD

**Issue by SirStudMuffin** [MyM-ModpackTeam/hypovolemia#188]
Getting in a coffin casuses NEI to go into meltdown

**Comment by johnfg12** [comment]
[crash-2016-06-15_12.14.06-server.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/315973/crash-2016-06-15_12.14.06-server.txt)
Server crash log

**Comment by johnfg12** [comment]
appears to be caused by world corruption
