### ISSUE TITLE
Minetweaker issues

### ISSUE THREAD

**Issue by johnfg12** [MyM-ModpackTeam/hypovolemia#189]

**Comment by johnfg12** [comment]
il sort this in a bit
![image](https://cloud.githubusercontent.com/assets/5445550/16078037/4ffef048-32f4-11e6-8fa2-12a68032cb7f.png)

**Comment by Bennyboy1695** [comment]
https://github.com/MyM-ModpackTeam/hypovolemia/blob/master/src/scripts/Misc.zs#L3
Missing the semicolon at the end ;)
https://github.com/MyM-ModpackTeam/hypovolemia/blob/master/src/scripts/witchery.zs#L4
Brackets aren't used in var's

**Comment by Slind14** [comment]
testing before commiting?

**Comment by johnfg12** [comment]
well that would work

**Comment by kindlich** [comment]
Fixed now, except for the things with Modtweaker 2 and the thaumcraft Arcane recipes...

**Comment by johnfg12** [comment]
any idea how to solve that issue?

**Comment by kindlich** [comment]
Well, that error just sais that one script tries to remove a non-existant recipe and that MT just ignores that line...

The script with that error is the "thaum_and_technomancy_wand.zs" in line 10 and 11
It tries to remove the recipe for creating the iron capped thaumcraft wand as its recipe exists twice: once for the wand from technomancy and once for the "normal" one...

Unfortunately I cant fix this, as the wand recipes are saved differently than normal arcane recipes

**Comment by Slind14** [comment]
@johnfg12 please be aware that everything after the erroring line is being ignored.  Hence you should remove the erroring one or move it to its own file.

**Comment by johnfg12** [comment]
yep its done on my local and just need to push
