### ISSUE TITLE
Investigate /help issue

### ISSUE THREAD

**Issue by johnfg12** [MyM-ModpackTeam/hypovolemia#190]
![image](https://cloud.githubusercontent.com/assets/5445550/16078285/eb42f486-32f5-11e6-8b11-8a7099b45436.png)
/help is refusing to work investigation is needed

**Comment by Slind14** [comment]
that's cofh I believe. Every 1.7.10 modpack has that, just ignore it like the others..

**Comment by johnfg12** [comment]
ive just tested with just cofh core and help still works

**Comment by johnfg12** [comment]
if i make a _SERVER in https://github.com/MyM-ModpackTeam/hypovolemia/tree/master/src/mods will it only compile then in the server version? 
http://minecraft.curseforge.com/projects/helpfixer < this appears to solve the problem
