### ISSUE TITLE
steel prerequisite problem in quests

### ISSUE THREAD

**Issue by bsulcer** [MyM-ModpackTeam/hypovolemia#197]
The quest that requires making basic transport pipes, which require steel, is an earlier prerequisite of the quest chain that provides the means to make steel.  That quest and the follow on quest to create an electric pump should be moved further down the line.

**Comment by johnfg12** [comment]
you can make steel with foundry and I've added a recipe to convert between recipes earlier

**Comment by johnfg12** [comment]
fixed in latest version
