### ISSUE TITLE
unusual configuration in exported options.txt

### ISSUE THREAD

**Issue by bsulcer** [MyM-ModpackTeam/hypovolemia#198]
The options.txt file exported when building the pack currently contains some rather unusual settings:

- master volume set to 0
- render distance at minimum (2 chunks)
- fancy rendering turned off

Are these intentional settings for the pack, or did they just leak in?

**Comment by johnfg12** [comment]
ye sorry ive been working on a new build system for the pack to make deployment faster il sort that out now :)

**Comment by bsulcer** [comment]
It looks like 436c019ddb543cefe6681931d86f475c0c58f999 resolves this.

**Comment by johnfg12** [comment]
ye it will be fixed in the next version :)
