### ISSUE TITLE
belladonna seeds from mutation not detected for quest

### ISSUE THREAD

**Issue by bsulcer** [MyM-ModpackTeam/hypovolemia#200]
The quest "Mutating into a Witch!" doesn't detect belladonna seeds obtained via mutation.  I tested both identified and unidentified seeds and neither are detected.  Giving yourself the witchery:seedsbelladonna item does work.

**Comment by GGothicRide** [comment]
did you make sure to use the latest github version, many of the hqm bugs have been fixed in this version

**Comment by bsulcer** [comment]
I can confirm that this is fixed by 2975c3f143470f39218feff7c8e3d490913c156b.

**Comment by GGothicRide** [comment]
i made sure to get the right detection method and the correct NBT data of the seeds that were meant to go there in the first place, thanks for bringing this up
