### ISSUE TITLE
There was a problem loading MFR Compat: Thaumcraft

### ISSUE THREAD

**Issue by Slind14** [MyM-ModpackTeam/hypovolemia#203]
http://pastebin.com/1fWy1n9h
Might need to be looked into, in case its gameplay relevant.

**Comment by chuggafan** [comment]
Shouldn't be relevant in the slightest, i'll have to check if MFR machines are scannable, as that is what it would affect, if someone else can do this before me that'd be great

**Comment by johnfg12** [comment]
il check now

**Comment by johnfg12** [comment]
seems fine to me
