### ISSUE TITLE
Structures without space blocks

### ISSUE THREAD

**Issue by Slind14** [MyM-ModpackTeam/hypovolemia#204]
**Relevant:** #206
RecurrentComplex has space blocks which can be place into a structures wholes in order to prevent from blocks at those locations when the structure is being placed which can look it got pasted. (flat cuboid ground around it)

The old structures make use of those blocks and it might be good to update the new ones to use those, too. 

I have been flying through the world and looking at the different structures, I did **not** see a huge need for this but if it improves the generation it isn't any harm as they need to be updated to the quadrum blocks anyway.

BoneHill_V1
BoneHill_V2
BoneHill_V3
BoneHill_V4
GothicsTower
NewStructure
(RandomSkelly_V1)
(RandomSkelly_V2)
(RandomSkelly_V3)
SandsCave

![image](https://cloud.githubusercontent.com/assets/3914677/16541494/de9e8a3c-4084-11e6-9675-36d6bd30f25b.png)
top with, below left without, below right with
![image](https://cloud.githubusercontent.com/assets/3914677/16541410/46ec2bec-4082-11e6-85a4-8b5701aba5c5.png)

**Comment by chuggafan** [comment]
@johnfg12 *claps*, please don't make your own mod, use the mod that worked before and get a way to fix it out with the creator, Slind, it appears that John did NOT account for this... i don't know how or why, it's happening because of how john is handling terrain generation atm, will check his repo to see how he's doing it and suggest fixes

**Comment by Slind14** [comment]
we already reverted to how it was before, but the new structures aren't like the old ones and something changed causing structures to spawn in the air. I just checked several mountains with the old version and it doesn't happen there.

**Comment by chuggafan** [comment]
Hmmmmm.... which mod is doing terrain generation? i'll check it out there, because i would expect this to be the same for both unless someone changed their terrarin generation code

**Comment by Slind14** [comment]
This is too complex to look over within a few minutes

**Comment by chuggafan** [comment]
Yes, i have a lot of spare time due to the summer, if anyone at all knows who is doing terrain generation, i can try to help from there, but otherwise i can't

**Comment by Slind14** [comment]
I went ahead and cleaned up the issue, in the process I removed the comments, @chuggafan why don't you join the team on slack #hypovolemia?

**Comment by chuggafan** [comment]
i'll try to find it then

**Comment by johnfg12** [comment]
thats my fault i couldn't not work out how to remove space from the structures how did u do it slind?

**Comment by Slind14** [comment]
I didn't create those, but those tiny blue blocks can be placed or set with a command.
