### ISSUE TITLE
Structures spawning in the air

### ISSUE THREAD

**Issue by Slind14** [MyM-ModpackTeam/hypovolemia#205]
Unfortunately there are some structures spawning in the air. I have been trying to figure out why but came up empty handed.

I do not know if this issue existed before two, I visited a few mountains with the untouched sw worldgen version and couldn't find anything like this. I might have been unlucky, though.

I compared the recurrent config and the structure files, they are identical including their encoding. 

The mod offers solid blocks which would be spawned as a sort of ground below the structure and could probably fix the flying, but it would still look wrong due to the pillar it would create.
In best case, it wouldn't spawn any structures at those cliffs. 
http://minecraft-recurrent-complex.wikia.com/wiki/Solid

It would be great if we could verify if this is a new issue or did exist with the untouched worldgen, too. As solving this without the solid blocks is a much cleaner and better looking solution.

![image](https://cloud.githubusercontent.com/assets/3914677/16541574/32275eca-4087-11e6-8bd3-5dbbc78feca7.png)

![image](https://cloud.githubusercontent.com/assets/3914677/16541735/db9a88e8-408b-11e6-95fb-648556c56525.png)

**Comment by johnfg12** [comment]
removed the structures causeing the problem and will redo some later
