### ISSUE TITLE
Dragon drops draconium dust

### ISSUE THREAD

**Issue by GGothicRide** [MyM-ModpackTeam/hypovolemia#211]
needs to be removed as a drop

**Comment by chuggafan** [comment]
can't fix, intentional

**Comment by GGothicRide** [comment]
it can be removed, we removed carrots and potatoes from mob drops

**Comment by chuggafan** [comment]
it's till intentional

**Comment by chuggafan** [comment]
*still, caithleen intended it, first way to get draconium after all

**Comment by drz2k** [comment]
Dragon or custom altar recipe. Correct.

Perhaps a single dragon for single player for balance.

**Comment by chuggafan** [comment]
Ehhhh by the time you get the draconic armor for the chaos dragon you have plenty of draconium, so i don't see a reason for 1 dragon only to exist

**Comment by drz2k** [comment]
"Farms"

**Comment by chuggafan** [comment]
There's more ways of getting draconium, but i won't say for reasons of my own, but seriously, you get less draconium farming the dragon each time, if you're trying to farm the spawning of the dragon, i've tested

**Comment by johnfg12** [comment]
we can remove it if it needs to be removed
