### ISSUE TITLE
Quest and crafting bugs

### ISSUE THREAD

**Issue by miner-bob-1960** [MyM-ModpackTeam/hypovolemia#217]
The quest book will not recognize that you have crafted the basic tank after crafting 1,
unable to craft Hippie dynamos as the mana coil, is redstone in a mana pool to craft, this is also the same recipe for mana powder

**Comment by johnfg12** [comment]
the first one has already been fixed

**Comment by johnfg12** [comment]
and does the mana coil recipe work?

**Comment by chuggafan** [comment]
no, ofc not john, recipie conflicts, minetweaker redstone -> mana powder out or fork latest botania for 1.7.10 and remove the recipie by hand, then package and say that you did x but all code is copyright respective owners blah blah blah legal disclaimer

**Comment by AllMightyPOWA** [comment]
Also, in digital blood tab wireless terminal doesn't register after being crafted

**Comment by TheIcyOne** [comment]
Or just fix the mana dynamo recipe instead, to avoid interfering too far with Botania's mechanics.

**Comment by krakel** [comment]
How can I craft on quest "Hydrogen chloride" on the second task the Brine Bucket. The Gaseous Brine was easy, but there is no recipe for the bucket.

**Comment by TheIcyOne** [comment]
Is it a crafting quest, or just detection?

**Comment by krakel** [comment]
Oh it will create with the Thermal Evaporation Plant (Salination Plant). But for this building we need the Advanced Solar Generator!

**Comment by chuggafan** [comment]
Known that it isn't there, and afaik @drz2k intended for it to be this way, last i checked

**Comment by tyler489** [comment]
@krakel make gaseous brine then condense it in to a fluid form then place in a bucket.

**Comment by chuggafan** [comment]
can't make brine without the thing tyler, remember that pain when we played last time?

**Comment by tyler489** [comment]
they fixed it now... theres actually a way to make it now.

**Comment by tyler489** [comment]
@johnfg12 
replace
     mods.botania.ManaInfusion.addInfusion(<technom:itemBO>, <minecraft:redstone>, 3000);
or 
     mods.botania.ManaInfusion.addInfusion(<technom:itemBO>, <ore:dustRedstone>, 3000);
or
     mods.botania.ManaInfusion.addInfusion(<technom:itemBO>, <ore:alloyBasic>, 3000);
with
     mods.botania.ManaInfusion.addInfusion(<technom:itemBO>, <Botania:manaResource>, 3000);

**Comment by johnfg12** [comment]
can we have these issues separated please because it gets incredibly hard if everyone puts it in one issue :)
@AllMightyPOWA @krakel
