### ISSUE TITLE
Shift clicking recipes doesnt work

### ISSUE THREAD

**Issue by SirStudMuffin** [MyM-ModpackTeam/hypovolemia#220]

**Comment by johnfg12** [comment]
some information would be useful :P

**Comment by SirStudMuffin** [comment]
When shift clicking the ? nothing happens with some recipes

**Comment by johnfg12** [comment]
What recipes?

**Comment by Sandstroem** [comment]
Had no issue with that so far. It usually doesnt work with items that do not stack. Lava buckets, blood orbs, etc

**Comment by johnfg12** [comment]
nei issue
