### ISSUE TITLE
Cleavers Uncraftable

### ISSUE THREAD

**Issue by SirStudMuffin** [MyM-ModpackTeam/hypovolemia#229]
Cant make the large sword blade!

**Comment by tyler489** [comment]
or the full guard (fillager item)

**Comment by SirStudMuffin** [comment]
Sword blade too

**Comment by SirStudMuffin** [comment]
Wide guard, Hand guard, Pan , Sign Head, Knife, chisel, Scythe, Arrow head, gem cast, nugget , shurikan,

**Comment by tyler489** [comment]
I think we should keep it the way @drz2k wanted it

**Comment by SirStudMuffin** [comment]
*CLOSE*
