### ISSUE TITLE
Spelling fixes

### ISSUE THREAD

**Issue by Delerium** [MyM-ModpackTeam/hypovolemia#23]
Lore book:
Welcome to hypovolemia lore page: 
"When you got an item" = "When you get an item"
"immediatly" = "immediately"
"followup" = "follow-up"
Bloodmagic:
"allways" = "always"
"avaible" = "available"

Quest book:
Intro text "If feels wrong." Should be "It feels wrong."
Tier 1:
Maybe if I regret my sins
"Whatever god feels to hear my regrets" = sounds odd. Perhaps:
"Whatever god decides to hear my regrets"
They must be joking!
"usefull" = "useful"
Wait plants?
"amusment" = "amusement"
Self confidence
"I start to think that I do not rely on the gods" = sounds better as:
"I start to think that I should not rely on the gods"
Tier 2:
Improving the Altar
"powerfull" = "powerful"

**Comment by tyler489** [comment]
Growing water in the seeds quest should read We are Almost there not allmost

**Comment by tyler489** [comment]
https://gyazo.com/afa00490f6800be69b34e5e9d2724795
should read It feels wrong

the coal seeds quest should read
Lets start with something I can already make.

**Comment by Nezraddin** [comment]
In the "Reagents"-Quest:
"Simple provide it was an orb" -> "Simple provide it with an orb"

**Comment by Bennyboy1695** [comment]
The draconic section in the quest book is spelt wrong http://i.imgur.com/U6gpuVw.png

**Comment by shadowpanther** [comment]
The promo poster (the one at http://forum.feed-the-beast.com/threads/1-7-10-hqm-survival-hypovolemia-something-bloody-closed-alpha.125160/):

* Font choice makes the last line read "PLEASE THE GOOS", whoever those goos are
* First line, "already"
* Last line, "please the gods *to get* a second chance"

**Comment by shaggy1395** [comment]
Would anyone mind if I took a crack at cleaning up some of the spelling and grammar?  I've got a fork set up, I just didn't want to step on any toes if it's already being done.

**Comment by tyler489** [comment]
I was going to but all my free time has been taken up 

@drz2k any objections.

**Comment by SirWilli** [comment]
Please create pull requests.
QuestBook can be found here: https://github.com/MyM-ModpackTeam/hypovolemia/tree/master/src/config/hqm
LoreBook here: https://github.com/MyM-ModpackTeam/hypovolemia/tree/master/src/config/LoreExpansion/lore
