### ISSUE TITLE
Quest Order change suggestion

### ISSUE THREAD

**Issue by BluCalculator** [MyM-ModpackTeam/hypovolemia#230]
In the Digital Blood chapter (#5), the first quest requires charged certus quartz. The second quest requires (uncharged) certus quartz. Since charged quartz is made from the uncharged, I think these two quests are the wrong way around.

**Comment by tyler489** [comment]
would require a quest book reset

**Comment by GGothicRide** [comment]
we would need Slind to reset the quest books

**Comment by Bennyboy1695** [comment]
You don't need slind to reset them, changes that are made to the book, for examp,e adding or removing quests forces a restart automatically because of the changes. Switching two quests shouldn't though

**Comment by GGothicRide** [comment]
will be taken care of
