### ISSUE TITLE
More uses for Zivicio (ingots

### ISSUE THREAD

**Issue by tyler489** [MyM-ModpackTeam/hypovolemia#233]
zivicio ingots have no uses so having a quest for it doesnt make much since

**Comment by kindlich** [comment]
we could add a zivicio sungularity for the Infinity catalyst if you want that xD

**Comment by tyler489** [comment]
that works

**Comment by tyler489** [comment]
and platnum as well

**Comment by bookerthegeek** [comment]
We need Icons/Textures for:
- [ ] Zivicio
- [ ] Platnum

Then we can get this fixed.

**Comment by Sandstroem** [comment]
we could add a quest that wants you to make all zivicio armor and tools

**Comment by johnfg12** [comment]
![singularity zivicio](https://cloud.githubusercontent.com/assets/5445550/16602479/63ce7094-430c-11e6-98ea-ed0f574afd17.png)
![singularity platnum](https://cloud.githubusercontent.com/assets/5445550/16602480/63ceafd2-430c-11e6-8cc0-6e38bb3ab98c.png)

textures

**Comment by bookerthegeek** [comment]
I'll get started on this tonight. The quests are a good idea also.

**Comment by SirStudMuffin** [comment]
Id add them to 0.1.7 instead of 0.1.6 so you have more time

**Comment by johnfg12** [comment]
how long do u think that will take booker?

**Comment by bookerthegeek** [comment]
Okay Doeky.

**Comment by johnfg12** [comment]
also https://github.com/SpitefulFox/Avaritia/blob/master/src/main/java/fox/spiteful/avaritia/items/ItemSingularity.java might help

**Comment by bookerthegeek** [comment]
Tomorrow night most likely.

**Comment by SirStudMuffin** [comment]
Ok we want the update pushed tomorrow so

**Comment by tyler489** [comment]
MAKE THE platnum one bluer/silver

**Comment by bookerthegeek** [comment]
Textures are up to @johnfg12

**Comment by bookerthegeek** [comment]
@johnfg12 
When using your image I get this as a crash:
`java.lang.RuntimeException: broken aspect ratio and not an animation`

So, otherwise, good to go. Once that gets fixed we can proceed.

[Full Crash](https://gist.github.com/bookerthegeek/abb37c4099399112c1d303c619778463)

**Comment by johnfg12** [comment]
umm is that quandrum(or however u spell it) ?

**Comment by tyler489** [comment]
Yeah.

**Comment by bookerthegeek** [comment]
Yep, quandrum....

No idea why the crash. Why not just call it a "super dense block of whatever, and color the edges of the block similar to 6x compressed cobble? Easier texture maybe?

**Comment by johnfg12** [comment]
does quandrum even support moving textures?

**Comment by bookerthegeek** [comment]
I do not believe so. That is why I suggest adding a compressed block,  no need to animate.

**Comment by Bennyboy1695** [comment]
Why not use resourceloader to overwrite a singularity already in the game

**Comment by johnfg12** [comment]
because we need a new one

**Comment by bookerthegeek** [comment]
The ones in game are all ready in use. Would be better to have the mod itself add a way to add additional ones. I'll go ask them to add that feature.

**Comment by bookerthegeek** [comment]
http://minecraft.curseforge.com/projects/thermal-singularities

Adds thermal expansion singularities 



https://github.com/SpitefulFox/Avaritia/issues/100
Request for configs.

**Comment by Bennyboy1695** [comment]
I can whip up a mod to add a few spare singularities if wanted.

**Comment by bookerthegeek** [comment]
That would be nice. If you could, could it just be the configs I suggested to the mod? This way e can add more later if we want to.

**Comment by chuggafan** [comment]
Is said mod with animations still neccessary? if so i can make one in my spare time

**Comment by bookerthegeek** [comment]
Yes please. Actually, if you could something along the lines of a configuration that let's players specify the color, name, base material and amount of the material. That would make it futare proof.

**Comment by chuggafan** [comment]
It'll take a bit of a while for me to do this as currently there is no MDK for 1.7.10 on forge's website to download

**Comment by bookerthegeek** [comment]
No worries. We'Lloyd lave this open till then.

**Comment by chuggafan** [comment]
I whipped up something, but it needs work, a lot of work, as in I have no idea how to make a config file that works for this, @johnfg12 if you could help with that that'd be great

**Comment by kindlich** [comment]
@chuggafan: for a config I'd think of either using a .json system or just arrays (never actually made any of those xD)

something like that for the arrays:

`#Names:["Minicio Singularity", "Whatever", "and more"]
#Colors:[#01A9DB, #8904B1, #DF01D7]
`

The inputs could later be added via MT xD

**Comment by chuggafan** [comment]
@kindlich i can't do the config stuff, someone can figure out the rest and PR it and i'll pack it and ship it out, as i'm working on other stuff atm

**Comment by bookerthegeek** [comment]
The configuration should be
````<display name>, <base material>, <amount of material>, <base color>, <secondary color>````

**Comment by chuggafan** [comment]
I can't do the config files, too confusing imho, not well enough documented

**Comment by Bennyboy1695** [comment]
That was the troubles i was having was the configs not be documented enough on how to create them, i have the mod all ready was just trying and failing to setup a json for it. I suggest using CustomThings to add them as it supports everything that is being looked for and is already an established mod

**Comment by bookerthegeek** [comment]
I could not get custom things to display animated textures.

**Comment by Bennyboy1695** [comment]
Did you have the mcmeta file detailing the animations frames ? I do know its possible though as ProjectOzone 2 uses customthings to add animated singularities

**Comment by johnfg12** [comment]
any update on this?

**Comment by johnfg12** [comment]
any update on this?
