### ISSUE TITLE
Version 0.1.3 double mod files

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#234]
Version 0.1.3 contain double files:
Mekanism-1.7.10-9.0.2.271   -   Mekanism-1.7.10-9.0.3.277
StorageDrawers-1.7.10-1.9.9   -   StorageDrawers-1.7.10-1.10.0

**Comment by johnfg12** [comment]
apparently curse didnt remove the old ones thanks for reporting :)

**Comment by krakel** [comment]
I got the files from GitHub!

**Comment by johnfg12** [comment]
ik i use curse :P
