### ISSUE TITLE
Error on Misc.zs:2

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#235]
```
ERROR: Misc.zs:2: Could not resolve <ExtrabiomesXL : slabRedRock ) ; recipes . removeShapeless ( < foundry : foundryMold : 7>
ERROR: Error loading Misc.zs: java.lang.NullPointerException
```
http://pastebin.com/PCSAZ2tv

**Comment by tyler489** [comment]
oops.

**Comment by johnfg12** [comment]
im going to slap him one of these days

**Comment by tyler489** [comment]
fixed

**Comment by krakel** [comment]
The next one. :)
`ERROR: Error executing Chisel.zs: null`

**Comment by tyler489** [comment]
https://github.com/MyM-ModpackTeam/hypovolemia/commit/ce15bd1846464dad937d295fab5f7f9180f9db70

**Comment by krakel** [comment]
I copy your changes, but the script error on misc.sz was not gone.

**Comment by johnfg12** [comment]
done

**Comment by krakel** [comment]
I think you got a script order problem. You have to change the first or all names from name.sz to 0-name.sz and so on. All files will parse in alphabetical order. There was also a hidden flag file ".sorting" . But I dont know this exactly.
