### ISSUE TITLE
Quest Split it up

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#236]
Item Electrolytic Searator was not detected. Need nbt_fuzzy. Got nbt info on crate!
The same problem on Yihaaaa. All mekanism item got personalised nbt info.
Storing Energy match any task with first item.

**Comment by tyler489** [comment]
#237

**Comment by SirStudMuffin** [comment]
*CLOSE*

**Comment by GGothicRide** [comment]
fixed in latest Comit im pushing for the HQM
