### ISSUE TITLE
Electrolytic Separator quest

### ISSUE THREAD

**Issue by AllMightyPOWA** [MyM-ModpackTeam/hypovolemia#237]
This item can't be detected by the quest book, I tried looking around and didn't find this bug so I'm opening a new Issue :)

**Comment by tyler489** [comment]
#236

**Comment by SirStudMuffin** [comment]
Item Electrolytic Searator was not detected. Need nbt_fuzzy. Got nbt info on crate!
The same problem on Yihaaaa. All mekanism item got personalised nbt info.
Storing Energy match any task with first item.

**Comment by tyler489** [comment]
all the mekanism quests will neede nbt fuzzy then @GGothicRide

**Comment by GGothicRide** [comment]
fixed in next Coomit im pushing
