### ISSUE TITLE
ghast seed recipe indirectly needs ghast tears

### ISSUE THREAD

**Issue by piraced** [MyM-ModpackTeam/hypovolemia#249]
basically ghast seeds<skeleton seeds<imperio essence<T4 blood orb<T4 altar<ritual of binding<elemental inscription tool air<ghast tear

**Comment by johnfg12** [comment]
yes u can find ghasts in the nether

**Comment by SirStudMuffin** [comment]
And the issue with this is? 1 ghast tear is needed thats it

**Comment by johnfg12** [comment]
after this being discussed in slack i though i would add you dont need a teir 4 altar you actuly need a teir 3
