### ISSUE TITLE
Detection of Botania Flowers in quests are still not correct

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/hypovolemia#252]
Once you do the first flowers in botania, all the quests on the lower left side, which want you to make multiple flowers, detect at the same time.

**Comment by GGothicRide** [comment]
i have checked the HQM detection methods for the quest bout functioning flowers, they work as they're supposed to, however this doesnt make any sense as to why they still detect without you having to make the flowers at all will need somebody to look further into this issue

**Comment by tyler489** [comment]
its because botana uses nbt data for the type of flower as well as a few other things unfortunitly hqm can detect between the data for some reason.. the only way to do this would be to set each flower as its own quest with match nbt for each
