### ISSUE TITLE
zombies drop carrots and potatoes still

### ISSUE THREAD

**Issue by tyler489** [MyM-ModpackTeam/hypovolemia#253]
currently in contact with the minetweeker dev as support was suppost to be added in 1.7 for mob drops

**Comment by tyler489** [comment]
alternitvely we could add this mod
http://minecraft.curseforge.com/projects/custom-mob-drops

**Comment by johnfg12** [comment]
https://github.com/MyM-ModpackTeam/hypovolemia/commit/abcf49086e683019b83db43a545b2f7281166ed4 
should already be fixed

**Comment by tyler489** [comment]
Yeah according to play3rs its not in 1.2

**Comment by johnfg12** [comment]
1.2 u mean 0.1.2? the 0 is important

**Comment by tyler489** [comment]
0 isn't important u knew what I mentioned :)

**Comment by johnfg12** [comment]
no it is because your saying were stable its versioning it is very important

**Comment by johnfg12** [comment]
i guess i should test this really well i guess i shall set up some super testing machine

**Comment by johnfg12** [comment]
ive test they dont.
