### ISSUE TITLE
The impossible Quest

### ISSUE THREAD

**Issue by tyler489** [MyM-ModpackTeam/hypovolemia#260]
Each infinity catalyst requres 8 pearls each ingot requres 11 catalysts

**Comment by bookerthegeek** [comment]
Pearls are not used up in crafting.

**Comment by tyler489** [comment]
the extreame pearl isnt used up?

**Comment by TheIcyOne** [comment]
Primordial pearls aren't used up by most Thaumcraft recipes.

**Comment by tyler489** [comment]
25x8 pearl for the pants alone sure u get them back but thats 200 PEARLS
Thats 100 Chaos dragons and 600,000,000,000 Blood

**Comment by bookerthegeek** [comment]
That is a lot of stuff. Yet not impossible.

**Comment by TheIcyOne** [comment]
That's only 8 pearls, isn't it? Since they don't use the pearls in the first recipe.

**Comment by bookerthegeek** [comment]
Correct
