### ISSUE TITLE
Push n' Pull detect wrong flowers

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#263]
This quest detect non crafted flowers. Nice I need only create two flowers. :)

**Comment by krakel** [comment]
All folowing quest detect wrong flowers.

**Comment by krakel** [comment]
Changing the Flow and all following quest match on any Lens and complete together.

**Comment by tyler489** [comment]
Known issue hqm bug

**Comment by SirStudMuffin** [comment]
I think gothic fixed this issue
Ill ask later

**Comment by krakel** [comment]
Its not a hqm bug. All wrong flower extect a precition option NBT_FUZZY, but the correct shoul be PRECISE!

**Comment by krakel** [comment]
The opposite problem was on all lens. Wrong precition FUZZE should be changed to NBT_FUZZY.

**Comment by tyler489** [comment]
If u change it to precise they don't detect that's what it was lrigionally
