### ISSUE TITLE
Thaumcraft Quests Wand not detected

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#267]
The first Quest at Thaumcraft expect a wand with NBT. The craftet wand dont have a NBT. With a match condition precise this wand will not detect!

**Comment by johnfg12** [comment]
this should be already fixed @GGothicRide is it fixed?

**Comment by tyler489** [comment]
Yes it's fixed when the server updates 

Also duplicate

Please check for simular posts
