### ISSUE TITLE
Change building block recipes

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/hypovolemia#268]
Ok, so I don't really like that you get marble from chiselling red rock. Also water and air essences could have more use, so I suggest some recipe changes:

1. Limestone, havent looked at the current recipe

Recipe on Regrowth: http://i.imgur.com/GXn9oWq.png

I suggest 2 Water over 2 Earth essences, give you 1 Limestone

2. Marble

Recipe on Regrowth: http://i.imgur.com/GK09hre.png

We can use this recipe, but only one marble, not 16.

3. Red cobble

I know there is plenty around, but I like building with this stuff and since there is no farmworld, I don't like running around in the overworld with my bound pick and mess up the landscape.

I suggest the following recipe: One red cobble is made in a 2x2 recipe, which needs 3 Fire essences and 1 dirt essence.Similar to the marble recipe above.

I haven't checked yet whether those suggested recipes create a recipe conflict.

**Comment by tyler489** [comment]
I'll do it

**Comment by Sandstroem** [comment]
All those recipes are wrong.

First: I suggested red cobble to be 3 fire and 1 earth, not the other way around.

Then also all of this recipes have been made shapeless. The recipes for cobble and sand etc are shaped. This needs to be fixed.
