### ISSUE TITLE
corpses fall torugh world

### ISSUE THREAD

**Issue by sonycc** [MyM-ModpackTeam/hypovolemia#271]
Corpses that are close to walls or underground tend to start glitching trough the world resulting in a lot of lost items

**Comment by johnfg12** [comment]
how did u die?

**Comment by sonycc** [comment]
^

**Comment by sonycc** [comment]
zombies, lava, creeper explotion have thus far caused the issiue

**Comment by johnfg12** [comment]
? what killed you?

**Comment by sonycc** [comment]
just now, zombie killed lukkse

**Comment by tyler489** [comment]
mod issue
