### ISSUE TITLE
Broken quests

### ISSUE THREAD

**Issue by sonycc** [MyM-ModpackTeam/hypovolemia#277]
The tanks you get from the quests "No end in sight" and "Headache" in chapter 4 have :100 at the end resulting in them being unsuitable for use in crafting

**Comment by tyler489** [comment]
noted should be fixed in next update @johnfg12 u fixed this right

**Comment by sonycc** [comment]
placing and breaking the tanks seems to fix the problem

**Comment by sonycc** [comment]
"now combine it" also gives such a tank

**Comment by johnfg12** [comment]
should be ok next update
