### ISSUE TITLE
Problem with Silverwood Sapling

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#280]
My first Silverwood Saplling dont have a node. So I harvest the complete tree. No new sapling was dopped. New Sapling you will get with the next quest for Silverwood Leave. :( But now I cannot get a new tree without a sapling. Or can I get new nodes from other places? The nodes from the other quest dont contain all aspects. :(

**Comment by johnfg12** [comment]
Maybe a second chance quest for it ? @ggothicride

**Comment by krakel** [comment]
I think the requirement for the quest Growing vis should be changed.

**Comment by tyler489** [comment]
Theres a second chance quest u get 100 sapljngs

**Comment by krakel** [comment]
1000 Shards of any type. Oh noo. :)

**Comment by johnfg12** [comment]
well you will have to do the second chance quests ;)
