### ISSUE TITLE
Performance Drop

### ISSUE THREAD

**Issue by AlexanderADM** [MyM-ModpackTeam/hypovolemia#284]
I'm not sure if this is the right place to raise the issue but I hope so.

With the new updates aka 0.1.6/0.1.7 I see you've removed FastCraft and this has a noticeable impact on the overall modpack simply because with FastCraft I get a stable 50/60 FPS and without it it drops down to 1 FPS effectively rendering it unplayable.

Not sure if you could do anything regarding it or not since some people are really not even capable of adding a mod. (Manually adding fastcraft fixed any performance issues)

P.S: not a potato PC got the modpack running with 4gb of RAM and runs stable with anything else.

**Comment by johnfg12** [comment]
http://docs.mym.li/en/latest/Knowledge_Base/debug.html

you can add fastcraft yourself the reason it was removed was the constant crashes that many players were noticing on start up. which forced us to remove it

**Comment by AlexanderADM** [comment]
And I totally failed in finding that, I did read the fact it was causing crashes and I understand that ( I did add fastcraft myself since it was causing no issues whatsoever for me).
I mainly raised the issue for the less powerful computers and players that don't even know what fastcraft is.
Sorry for wasting time though.

**Comment by johnfg12** [comment]
np :) were here to help if you could run the profiler i would appreciate it preferable without fastcraft :)

**Comment by AlexanderADM** [comment]
Here we go around 7-8 minutes of the profiler while trying to do something in-game.
https://drive.google.com/file/d/0ByGwECAYuZc9bEZjcFRvMVZfQTg/view?usp=sharing
Also a thread dump:
http://pastebin.com/aNi7BcaZ

**Comment by johnfg12** [comment]
thanks :D

**Comment by johnfg12** [comment]
![image](https://cloud.githubusercontent.com/assets/5445550/16713102/a487b088-4694-11e6-8175-b4cf9acf13c1.png)
seems to be a litlle over the top

**Comment by johnfg12** [comment]
@AlexanderADM can you try adding http://minecraft.curseforge.com/projects/cofhtweaks to you game

**Comment by johnfg12** [comment]
![image](https://cloud.githubusercontent.com/assets/5445550/16713119/2f9c9d1e-4695-11e6-8714-c8f0eaf77902.png)

**Comment by AlexanderADM** [comment]
Adding CoFHTweaks didn't seem to change much first of all I had trouble selecting the world seems like I had to click an exact pixel or something, but it seems to have slightly increased the chunk updates even though they are not loading at all unless I walk towards them, also a 1FPS increase! (fluctuating constantly from 1 to 3 FPS)

**Comment by johnfg12** [comment]
hmm intresting it seems to be cofhs hacky stuff + thaumcraft

**Comment by AlexanderADM** [comment]
If it's of any help I actually don't have any thaumcraft stuff going on in the current world and the same FPS/Performance drop happens in a newly generated world. I'm also doing another sample with CoFHTweaks right now.

**Comment by AlexanderADM** [comment]
And I realized I derped, you've asked for a profiling and I did the sampling - going to do the profiling as well.

**Comment by johnfg12** [comment]
:) thanks for the help

**Comment by AlexanderADM** [comment]
Okay so sampling with CoFHTweaks:
https://drive.google.com/file/d/0ByGwECAYuZc9LXlVSTgyYjJtLTQ/view?usp=sharing
Profiler with CoFHTweaks:
https://drive.google.com/file/d/0ByGwECAYuZc9cEpQU09HN0ExNEU/view?usp=sharing
Also nearing the end of the profiling the game suddenly crashed not to mention it being constantly not responding during the profiling
Final log(over 512kb too large for pastebin):
https://drive.google.com/file/d/0ByGwECAYuZc9MmNsMlRTSFA2UFE/view?usp=sharing

**Comment by AlexanderADM** [comment]
Also CoFHTweaks + Fastcraft = invisible textures

**Comment by johnfg12** [comment]
ye i wouldnt mix them

**Comment by johnfg12** [comment]
im  going to tag @Slind14 here as hes better at this stuff then me. slind can u give this a look over this and see if anything jumps out at you? please

**Comment by chuggafan** [comment]
if it's being stuck on OpenGL calls there's nothing you can really do except upgrade your GPU as your GPU isn't made for the newest OpenGL Vertex Buffer Objects (most likely VBOs, haven't seen the code), what system are you running, specs? RAM allocated?

**Comment by AlexanderADM** [comment]
The CPU might be a bit low but here are the specs :
CPU : AMD Athlon X2 215 2.7GHZ(dual core) 
GPU: AMD R7 260X
RAM: 16 GB DDR3(1866Hz) (HyperX Fury) assigned 4 GB to minecraft

**Comment by chuggafan** [comment]
I think it's the CPU being a bit on the hind end of "good" (considering my CPU from 2009 is 3.4ghz, 4 core), but otherwise i have no idea

**Comment by xulatis** [comment]
I had a similar issue with the modpack. I found out by changing the "MipMap Level" under Options from "4" to "0" reduced the OpenGL times significantly and boosted my FPS from sub 1 fps to ~30-40 fps.

**Comment by AlexanderADM** [comment]
Well the MipMap Level worked in some way as in I can go up to 3-9 FPS now so I can maybe move around, the chunks around still don't load even after 5 minutes unless I walk into them.

Hopefully in 2 weeks I'll have the new CPU and come back with some better data and certainly better FPS.

Thanks again for the tip @xulatis

**Comment by tyler489** [comment]
Im going to close  this for now if i can figure out why fastcraft is crashing people ill re add fastcraft any more issues feel free to comment them here.
