### ISSUE TITLE
missing autopacker

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#285]
Can you add a autopacker? The Compacting Drawer dont work with essences.

**Comment by johnfg12** [comment]
do u have any suggestions?

**Comment by kindlich** [comment]
there's automagy -> golem workbench

**Comment by krakel** [comment]
The standard: http://mods.curse.com/mc-mods/minecraft/221457-autopackager :)

**Comment by tyler489** [comment]
Use mfr liquidcrafter

**Comment by krakel** [comment]
The liquidcrafter is for recipes with liquid containers (buckets, cells, etc.)!

**Comment by drz2k** [comment]
Suggest it as a feature to the Storagedrawers devs/use MACs in the meanwhile ;)

**Comment by kindlich** [comment]
the liquicrafter works with everything!

**Comment by krakel** [comment]
I will test the liquicrafter. But it hold only one recipe. A autopacker works on all 2x2 or 3x3 recipes!

**Comment by drz2k** [comment]
Same goes for MACs but you can upgrade their speed at least.

**Comment by krakel** [comment]
What mean to be a MAC? 
Compacting Drawer can not work on essences, because the work in both directions and there is only one recipe for combine these.

**Comment by Messiah7** [comment]
I know that some servers have performance problems when using Autopackager, may be less resource will Compacter http://minecraft.curseforge.com/projects/compacter
While I believe that both of them will be superfluous here, besides many essences have shapeless and shape recipe

**Comment by drz2k** [comment]
Molecular Assembly chamber ... standalone mode in this case

**Comment by tyler489** [comment]
people can use the mfr liquidcrafter like i did.. works great

**Comment by krakel** [comment]
please check commit https://github.com/MyM-ModpackTeam/hypovolemia/commit/52951308b6b52d3c383d1d927a633f5745a61fba

**Comment by Sandstroem** [comment]
According to this commit comment, you need to put in another version of autopackager

https://github.com/MyM-ModpackTeam/hypovolemia/commit/52951308b6b52d3c383d1d927a633f5745a61fba

**Comment by bookerthegeek** [comment]
Easier issue is going to be to add the missing recipes to the compacting drawers.  That will be preferable then adding another mod.

**Comment by bookerthegeek** [comment]
@johnfg12 if you take that back out I'll get the recipies added tonight

**Comment by SirStudMuffin** [comment]
doesnt mekanism have an autocrafter?

**Comment by drz2k** [comment]
autoPACKER!=autoCRAFTER

**Comment by krakel** [comment]
I see not the problem. @johnfg12 installed autopackager-1.6.3 (for 1.10). He only need replace/downgrade this file to autopackager-1.5.9a (for 1.7.10). Thats all.

**Comment by drz2k** [comment]
The "problem" is an additional mod that can cause issues, maybe isnt maintaned anymore and needs updating/downgrading for a SINGLE task you could achieve with the tools you already have. 

In my opinion I wouldnt have added the autopackager for this single reason. Bookers approach is the most work heavy but best one in my eyes. And since he already offered to do the work ... ;)

**Comment by kindlich** [comment]
@drz2k: To re-enable the compacting drawers being able to convert you just have to re-add the block-> Essence recipe, which is disabled via MT...

I don't know why, but it was replaced with an alchemic chemistry set recipe that does the same but costs 1000LP

So generally, re-enabling would prevent that recipe from being used!

![recipes](https://cloud.githubusercontent.com/assets/10351787/16924226/82b1c67a-4d1e-11e6-8654-b4514bc8e49e.PNG)

**Comment by drz2k** [comment]
Oh yeah, those are actually important for balance.
Thought the whole time the OP was talking about stacking some earth essence or stuff :D

**Comment by kindlich** [comment]
In what way are they important for balance?
Do those blocks do anything special (never really got into magicalcrops)?

And wasn't the recipe remove thing only to prevent the infusion stone recipes?

**Comment by drz2k** [comment]
It was for forcing the player to use bloodmagic for the upper magic crop tiers.

**Comment by kindlich** [comment]
Yeah that, but not the block->essence recipe xD

thought you meant that was somehow op and unbalancing...

**Comment by bookerthegeek** [comment]
@johnfg12 what was the verdict on what we are doing?

**Comment by krakel** [comment]
I do not understand the relationship between your changes on the essence basis recipes and the compacting of all other essences to ore, redstone, obsidian, etc. The compacting drawer need bidirectional recipes and can not used. The only other choice we have with AE2 auto crafting.  For ca. 30 recipes we get a big system cost.

**Comment by tyler489** [comment]
Or mekanism
