### ISSUE TITLE
Hqm

### ISSUE THREAD

**Issue by maciek198** [MyM-ModpackTeam/hypovolemia#287]
the digital blood line is bugged for me it shoew 100% completion but 2nd quest dosnt open

**Comment by tyler489** [comment]
Pictures please

**Comment by maciek198** [comment]
http://imgur.com/a/TW6EL

**Comment by johnfg12** [comment]
seems to work ok for me could this be a hqm bug?

**Comment by maciek198** [comment]
might be they was changing and updating the hqm so might be some kind of glich or bug

**Comment by tyler489** [comment]
cant reproduce but i changed some dependancys in the next version so it might be fixed then feel free to reopen if u have this issue again

**Comment by maciek198** [comment]
ok ok guys it was easly fixed dont worry it was 20 sec job

**Comment by maciek198** [comment]
needed to only do force completion thats it
