### ISSUE TITLE
molten iron quest

### ISSUE THREAD

**Issue by SirStudMuffin** [MyM-ModpackTeam/hypovolemia#288]
Wrong iron

**Comment by johnfg12** [comment]
what iron should it be?

**Comment by krakel** [comment]
You have to change the quest Iron For Days again. Molten Iron can not create. Its fluid from Tinker Smeltery. You should replace all Molten fluids with Liquid fluids from Foundery (all rewards and requirements)! I tested the last quest book.

**Comment by SirStudMuffin** [comment]
Thank you for your reply, as you can see this issue has been closed so it has already been fixed for next update

**Comment by krakel** [comment]
Its not fixed. I checked out the latest version of the quest book. https://github.com/MyM-ModpackTeam/hypovolemia/commit/c1b466cabcf50f7db8cb2e08c4e1e8062b1d5604

**Comment by tyler489** [comment]
No you didnt... I fixed it last week in the update we haven't pushed yet
