### ISSUE TITLE
Quest "Easing Life" asks for wrong tank

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/hypovolemia#289]
I am pretty sure that we don't want people to craft ultimate fluid tanks in an easy introduction questline. This should be changed to the Basic Fluid Tank.

**Comment by SirStudMuffin** [comment]
Worked fine for me

**Comment by Sandstroem** [comment]
So why does it ask for an ultimate fluid tank but the normal one also detects?

**Comment by World2LiveBy** [comment]
I have this issue in the 2.0 release, though it doesn't detect the normal one either. I crafted both the normal and the ultimate twice, once on a vanilla bench and once on tinkers bench. The quest still is marked as uncompleted. This is my first time reporting a bug, so let me know if I'm supposed to make an open issue instead.

**Comment by SirStudMuffin** [comment]
Ive reopened the issue for you and will get someone to look at it

**Comment by World2LiveBy** [comment]
Thank you. Let me know if you need pictures / anything else.

**Comment by SirStudMuffin** [comment]
Which ones have you tried making?

**Comment by SirStudMuffin** [comment]
Also some screenshots would help thanks

**Comment by World2LiveBy** [comment]
Every tier up to ultimate, so basic, advanced, elite and ultimate.
![ultimate](https://cloud.githubusercontent.com/assets/22865813/19416102/3c291008-934d-11e6-80ff-7b24d0b14a01.png)

![ultimate](https://cloud.githubusercontent.com/assets/22865813/19416113/6775744a-934d-11e6-85eb-4b18e7faa268.png)

**Comment by SirStudMuffin** [comment]
your using the latest version?

**Comment by SirStudMuffin** [comment]
try placing it and breaking it

**Comment by World2LiveBy** [comment]
yes. 0.2.0 through ftb. Running on minecraft 1.7.10.

Placing and breaking them didn't fix it. Though they now all list me as the owner if that is relevant.

**Comment by SirStudMuffin** [comment]
sometimes placing items changes the ID.
For a temporary fix do /HQM edit and auto complete it

**Comment by World2LiveBy** [comment]
Okay. Thank you. As a side note though, would placing and picking it up not change anything, since it is a crafting quest, not a detection one?

**Comment by SirStudMuffin** [comment]
Is changes the NBT value which may of been the issue but it apears not

**Comment by World2LiveBy** [comment]
The no more bones quest is broken for me as well - it asks for bedrock, and gives an invalid item. I don't know if that is supposed to be fixed or if it is related at all.

**Comment by SirStudMuffin** [comment]
Ill go talk to the team as they issues where apparently fixed in 1.9

**Comment by YourMCGeek** [comment]
Its fixed. Done.

**Comment by johnfg12** [comment]
since mcgeek says this is fixed il close this
