### ISSUE TITLE
Right click item harvesting still places blocks

### ISSUE THREAD

**Issue by Delerium** [MyM-ModpackTeam/hypovolemia#29]
Right click events aren't being halted when harvesting oreberry bushes or agricraft plants. This causes you to place blocks and torches accidentally.  As with the others, this is probably a mod bug and not fixable in the mod pack, but I figured I'd post it.

**Comment by drz2k** [comment]
Indeed modbugs/how they interact with mc - but at least for agricraft it seems fixed :)
