### ISSUE TITLE
Quest The normal way is missing

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/hypovolemia#290]
Someone removed the normal way to get into thaumcraft, which gave the player 5 or 6 nodes, but no deconstruction table

**Comment by johnfg12** [comment]
![image](https://cloud.githubusercontent.com/assets/5445550/16728031/fe67bdec-475b-11e6-9c4b-3817ca0dedff.png)
it still does?

**Comment by Sandstroem** [comment]
The rewards should be as in the old version. 

Also, I think in the simple way it is now a detection task and you keep the Thaumonomicon, but I have to check that.

I think it was a consume task before to keep it similar to the "cheaty way" where you handed in the Thaumonomicon in exchange for a cheaty one.

**Comment by Sandstroem** [comment]
Oh wait, you are telling me that this quest is still there?

Then I think the simple way autodetects the book and immediately hides the other option? That might be the reason why it was a consume task.

**Comment by tyler489** [comment]
Oh wait, you are telling me that this quest is still there?

Then I think the simple way autodetects the book and immediately hides the other option? That might be the reason why it was a consume task.
Yeah if u compleate the easy way u get 2 nodes  but locks normal

**Comment by Sandstroem** [comment]
Yes, but the issue is that I did not complete the easy way. It autodetected. The quest needs to be changed back to a consume task.

**Comment by tyler489** [comment]
Interesting it didnt do that for me ill check my sp tonight

**Comment by tyler489** [comment]
fixed it was set to autodeteect
