### ISSUE TITLE
Nether Ores crash

### ISSUE THREAD

**Issue by UnplacedTM** [MyM-ModpackTeam/hypovolemia#292]
While scanning Ardite/Cobalt ore with the Thaumometer you get an instant crash of the game (exits to the MyM-Launcher (easily said it just closes minecraft))

**Comment by johnfg12** [comment]
crash log? http://mym.li/crash

**Comment by Bennyboy1695** [comment]
please post your crash report, http://mym.li/crash if you dont know how

**Comment by UnplacedTM** [comment]
My apologies for the late response.

http://pastebin.com/cF0Ej5d0
