### ISSUE TITLE
Impossible quest Dragons Heart

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#295]
You need for this quest 100 Dragon Hearts. So you need 400 Mob Souls. The drop chance for Mob Souls was setting to 1000. So you have to kill 400.000 mobs for all. Is there a Mobgrinder, which can do it for you?

**Comment by Bennyboy1695** [comment]
reaper 5 on a sword will increase your soul chance.

**Comment by UnplacedTM** [comment]
Since I don't want to do another issue page since it's the same quest , but unfortunately that quest requires 100 Green Heart canisters and there's no recipe for those... eh

**Comment by chuggafan** [comment]
100 dragon hearts: chaos gaurdians

**Comment by SirStudMuffin** [comment]
The Green Heart canisters are the issue here

**Comment by tyler489** [comment]
10/10 yellow heart surrounded by nether star block for the green heart?

**Comment by chuggafan** [comment]
aren't those obtainable through like the dragons? I remember that being so, iirc their obtainable SOMEHOW, i just don't remember how

**Comment by tyler489** [comment]
dragons drop yellow hearts as far as i know green hearts are NYI on obtaining them

**Comment by SirStudMuffin** [comment]
Green hearts are normally disabled unless they become enabled

**Comment by tyler489** [comment]
fixed https://github.com/MyM-ModpackTeam/hypovolemia/commit/986763feb3c7be2718a6642285b54bc236ff65bc
