### ISSUE TITLE
Dynamic Tank mekanism not working,

### ISSUE THREAD

**Issue by sonycc** [MyM-ModpackTeam/hypovolemia#296]
might just be me not making it correctly but there's no recipie for dynamic glass

**Comment by tyler489** [comment]
try these recipys http://wiki.aidancbrady.com/wiki/Dynamic_Glass

**Comment by sonycc** [comment]
didn't work

**Comment by tyler489** [comment]
ill look into it trying to fix the quests giving unusable tanks

**Comment by tyler489** [comment]
what do u need the tank for?

**Comment by sonycc** [comment]
wanted to drain the blood ocean using 4 fully upgraded tanks and then just have it in a tank to sowly feed into my altars

**Comment by SirStudMuffin** [comment]
Structural glass works as a replacement

**Comment by Messiah7** [comment]
Try: 1 bucket in center and 4 steel ingot from each side
work for me
