### ISSUE TITLE
Clear glass not craftable

### ISSUE THREAD

**Issue by Akaistos** [MyM-ModpackTeam/hypovolemia#297]
Hello,

currently clear glass is not craftable. You need molten glass (which you only get from the [banned!] smeltery). You could also craft the clear glass blocks in the Foundry Metal Caster... but again with molten glass. When you smelt the glass with the induction crucible furnace you get "liquid glass" which turns into normal glass again in the metal caster... that's useless. Would be nice if you could change the recipes, so that we can get clear glass by smelting the regular glass. Because who smelts glass... to get the same glass again? :)

As stated, this is just a minor annoyance (for builders).
Thanks for your attention.

**Comment by chuggafan** [comment]
have you tried the clear glass from extra utilities instead?

**Comment by Akaistos** [comment]
There is no extra utilities. I can only find the tinkers construct clear glass.
With chisel you get one that looks similar to the clear glass (from tinkcon). But I'd still appreciate it if the clear glass gets implemented - well, made craftable.

**Comment by chuggafan** [comment]
clear glass from what mod then? i thought clear glass was from Ender IO or TiCon, and since you can make the TiCon one by chisel, isn't that a fix?

**Comment by Akaistos** [comment]
You either get clear glass with "Foundry" (metal) caster. But you need molten glass for that. You only get molten glass with the smeltery. The smeltery is deactivated tho. (not craftable).
This is why you can't craft it and there is no work around. You can liquid glass - but that just turn into regular glass again. I mentioned it already, that the smeltery is not available.
Chisel turns regular glass into other glass-sorts... there is one that looks similar - but still it is not THAT clear glass.

**Comment by tyler489** [comment]
give me a min ill add it to the chisel whitelist

**Comment by tyler489** [comment]
Fixed in next version
