### ISSUE TITLE
"Iron For Days" (Second Chance) can't be completed

### ISSUE THREAD

**Issue by Akaistos** [MyM-ModpackTeam/hypovolemia#298]
Hey,

for the quest "Iron For Days" you need molten iron - which can only be obtained by the smeltery, the smeltery is not craftable however. You can only get "liquid iron" with the "induction crucible furnace" [Foundry mod], if you deliver that liquid to the Quest Delivery System it won't count as "molten iron". 
So, currently it's not possible to deliver the requested 100.000mb molten iron.

**Comment by tyler489** [comment]
known issue should be fixed in the next update

**Comment by Sandstroem** [comment]
According to players on FTB this is not fixed in the current version.
