### ISSUE TITLE
Dancing for the god quest unable to turn in

### ISSUE THREAD

**Issue by risenation** [MyM-ModpackTeam/hypovolemia#303]
the quest required a bound blade. to turn in I made the blade and tried to turn it in in the activated and de activated state wont let me I even gave the blade to a friend who is playing with me to see if it would work for him but he had same result we are playing on the mym server

**Comment by tyler489** [comment]
Has to be unbound and deactivated..

**Comment by risenation** [comment]
I just tried that it didn't work

**Comment by tyler489** [comment]
Interesting worked for me ill look into this

**Comment by risenation** [comment]
Thanks yea ï even gave it to a friend to try same results as me

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 14, 2016 at 1:53 PM, tyler489<notifications@github.com> wrote:   
Interesting worked for me ill look into this
