### ISSUE TITLE
Broken text, Guide API, maybe downgrade?

### ISSUE THREAD

**Issue by Messiah7** [MyM-ModpackTeam/hypovolemia#305]
Is it possible downgrade Guide-API to a stable build 20 (Guide-API-1.7.10-1.0.1-20.jar)?
In the current build of 29 problems with the display of the text, it was not in the old build.
Also https://github.com/TeamAmeriFrance/Guide-API/issues/21
### **Build 20**
![2016-07-14_22 40 57](https://cloud.githubusercontent.com/assets/6631377/16849827/b9a08b00-4a15-11e6-8971-074f4b8c04d4.png)
![2016-07-14_22 41 16](https://cloud.githubusercontent.com/assets/6631377/16849832/bd5c0c1a-4a15-11e6-9b02-9c944e2c4616.png)
### **Build 29**
![2016-07-14_22 48 41](https://cloud.githubusercontent.com/assets/6631377/16849849/c8ef9056-4a15-11e6-9625-f7bdb417c30b.png)
![2016-07-14_22 48 25](https://cloud.githubusercontent.com/assets/6631377/16849850/cb2fc9a8-4a15-11e6-808e-77e42ffbcca7.png)

**Comment by SirStudMuffin** [comment]
Funny thing is the same happens with the witchery books
the black blocks i mean

**Comment by Messiah7** [comment]
Try take off armor and check the book
https://www.reddit.com/r/feedthebeast/comments/4rhle3/anyone_know_what_is_up_with_this_guide_api_book/

**Comment by tyler489** [comment]
No armor still happens

**Comment by SirStudMuffin** [comment]
Same with witchery

**Comment by Messiah7** [comment]
https://github.com/TeamAmeriFrance/Guide-API/issues/28
Anyone can try installing Unicode Font Fixer and see what happen?http://minecraft.curseforge.com/projects/unicode-font-fixer
I can not check because I have no problem with blacked text

**Comment by tyler489** [comment]
didnt work downgraded guiapi please open a new issue if the issue persists after the update
