### ISSUE TITLE
Tier 6 Crystall Cluster Xtreem Crafting

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#307]
The Crystal Cluster can create with the old recipe and also the xtreem crafting one. I think the first should be deactivied?

**Comment by chuggafan** [comment]
old one can't be crafted as no damned ritual, so it's not neccessary to remove the old recipie

**Comment by SirStudMuffin** [comment]
Please explain how you get the crystals if you cant do the invasion?

**Comment by krakel** [comment]
I tested the recipe. You deactivated the invasion???

**Comment by chuggafan** [comment]
the invasion has been deactivated since alpha .14 or so, aka before the pack was even public, so yes
