### ISSUE TITLE
Idea: add Avaritia recipe for Infinity egg

### ISSUE THREAD

**Issue by SirStudMuffin** [MyM-ModpackTeam/hypovolemia#311]

**Comment by chuggafan** [comment]
infinity eggs are unneccesary, as you can go above 20k altar power without them, which is more than any ritual you'll ever do

**Comment by kindlich** [comment]
The Bloodorb of the Armok is unnessecary as well, you can keep your network filled without it as well xD

**Comment by johnfg12** [comment]
a recipe suggestion would be good?

**Comment by kindlich** [comment]
![infinity egg](https://cloud.githubusercontent.com/assets/10351787/16902411/19dbb054-4c5e-11e6-883d-04119ed6f7f6.jpg)

What about that?

**Comment by chuggafan** [comment]
either way the infinity egg is still litterally useless, why would you make one when you already have 2x the ammount of altar power you will ever need?

**Comment by bookerthegeek** [comment]
Poops & Laughs

That's why @chugga_fan 


I'll add the recipe tonight with slight variation.

**Comment by johnfg12** [comment]
maybe i want to do 8 rituals right after one another?

**Comment by SirStudMuffin** [comment]
lel

**Comment by kindlich** [comment]
So... shall we add a recipe or not?

**Comment by tyler489** [comment]
theres no way to get dragon eggs is there?
