### ISSUE TITLE
Lilith cant spawn and Ellie glitches out and stops moving

### ISSUE THREAD

**Issue by SirStudMuffin** [MyM-ModpackTeam/hypovolemia#314]

**Comment by chuggafan** [comment]
Lilith can spawn, ellie needs to be respawned and put into lava, i've tested, known witchery bug, so close this

**Comment by SirStudMuffin** [comment]
Chugga i spend 2 hours trying o get her to spawn, she spent 20 minutes in the lava

**Comment by chuggafan** [comment]
It works for me

**Comment by SirStudMuffin** [comment]
ill try one more time later, 4th and last time

**Comment by tyler489** [comment]
added spawn egg using ritual ingrediants
https://gyazo.com/8e7c484f7baf389668f9e1cd5a1521de

**Comment by chuggafan** [comment]
Adding the spawn egg is useless as the ritual works

**Comment by tyler489** [comment]
tried it myself chugga elly disapeared in the nether but never conferted

**Comment by chuggafan** [comment]
O.o that's weird, should work, ehh i'll let you do it then
