### ISSUE TITLE
Quest Biofuel liquid not craftable

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#315]
The quest neat the fluid biofuel. The Biofuel Generator has no recipe! Or is there a other way?

**Comment by SirStudMuffin** [comment]
Ive seen people with made bio generation

**Comment by krakel** [comment]
NEI say no?!

**Comment by Messiah7** [comment]
You need BioReactor for craft biofuel, just Biofuel Generator for generate energy

**Comment by krakel** [comment]
Ah, the BioReactor has a recipe and can be crafted, the Biofuel Generator not. Thanks, I only need Biofuel.
