### ISSUE TITLE
the induction crucible furnace and ore berries

### ISSUE THREAD

**Issue by raven235** [MyM-ModpackTeam/hypovolemia#321]
if ya put ANY of the berries in the ICF you get nugget value's of liquid metal as opposed to the ingots ya get from normal furnace's

**Comment by Bennyboy1695** [comment]
ore berries are the equivalent of a nugget of that ingot so getting a nugget should be the correct value

**Comment by raven235** [comment]
not in this pack iron berries are = 3 ingots each  and all other =2 each
