### ISSUE TITLE
Forbidden magic caps Quest

### ISSUE THREAD

**Issue by SirStudMuffin** [MyM-ModpackTeam/hypovolemia#324]
Second Chance - Forbidian caps are neat
Cant make vitium wants as no Ars Magica

**Comment by miner-bob-1960** [comment]
Vinteum Caps, are a Ars Migica wand cap, they needed for both the Forbidden Caps Are Neat and Is It Worth IT quests.
 Just to be clear, Forbidden magic adds everything EVEN if the mod its self is not added. so there is no way to craft the 1100 caps.

**Comment by tyler489** [comment]
Fixed
