### ISSUE TITLE
Bloodmagic Reverence of the Condor interfering with /Fly

### ISSUE THREAD

**Issue by ZippityDoodah** [MyM-ModpackTeam/hypovolemia#325]
I was flying around (using my perk /fly) looking for creepers to kill when I got close to Lato_Diafol's base where he/she had a Bloodmagic Reverence of the Condor ritual active (creative flight)... Once I got out of range of the base I lost all flight and fell... This happened twice, the 2nd time killed me due to fall damage... 

Once you leave the sphere of influence, the /fly command is completely disabled... I had to type out the command again to Enable it again... I was not aware he/she had this ritual going or that it would interfere with the /Fly perk...

I had flown by his/her base earlier and wondered why I took damage for no reason, so I was working with him/her to determine what might have caused the damage... The only thing that seemed out of sorts was the flight issue..

Zip

**Comment by SirStudMuffin** [comment]
Server issue not modpack

**Comment by tyler489** [comment]
MOD ISSUE

**Comment by SirStudMuffin** [comment]
Not really, it happens on all packs
The flight of the condor overrights the creative level flight as it is a new flight

**Comment by chuggafan** [comment]
This is a mod issue but won't be fixed, as blood magic has moved on to 1.9/1.10, it's also technically a server issue, happens with litterally every single mod's form of flight except its own flight, so it WON'T be fixed

**Comment by tyler489** [comment]
happens with litterally every single mod's form of flight except its own flight, so it WON'T be fixed
thats what i told stud... although mym might be able to hotfix it

**Comment by ZippityDoodah** [comment]
Wouldn't it be a MOD running into Server Setup issue? Since /Fly is a perk offered by the MyM Dev's, not the Mod Creator... So are you implying the issue will not be fixed by the MyM Dev team on their end or are you being more specific with regards to the Mod Creator fixing something on their end?

I just wanted to ensure the MyM folks were aware of the issue, and maybe perhaps work on some server side solution...

Zip

**Comment by tyler489** [comment]
While you are correct /fly is a mym thing items such as botania's tiara and extra utils rings are also having this issue makes this a mod issue as bloodmagic has a unrecognised method of flight.

**Comment by ZippityDoodah** [comment]
I'll post this issue on the MyM Forums then... Thanks...

Zip
