### ISSUE TITLE
Ultimate Price Quest

### ISSUE THREAD

**Issue by miner-bob-1960** [MyM-ModpackTeam/hypovolemia#326]
I just completed this quest, just to make it clear I'm posting some pics
http://i.imgur.com/rHLGF35.png
and as a reward you should get the The Blood Orb Of Armok
http://i.imgur.com/fUqp56J.png
But I got this Invalid Item
http://i.imgur.com/qsrYtsH.png

image updated

**Comment by SirStudMuffin** [comment]
Last image is unavailable

**Comment by tyler489** [comment]
looking in sp and it worked for me ? Mod issue or server issue

**Comment by Sandstroem** [comment]
I made a ticket some days ago about this. @Sir-Will investigated, but he couldn't find the issue about this. I think the player got his orb now, we will have to see whether this was just a random glitch or will come up again. I guess @miner-bob-1960 is the first and probably only player that got to this quest now or is able to craft the item.

**Comment by miner-bob-1960** [comment]
As far as I am aware I was the first to complete the quest, on the MYM server, and there is only 1 other person that is close to completing it. As for the reward Admin spawned in the Orb for me.
