### ISSUE TITLE
What is the plan for Amber

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#329]
How can I get Amber? The only choise I found Blood Magic Meteor and Laserdrill.

**Comment by tyler489** [comment]
what u need it for?

**Comment by tyler489** [comment]
currently working on this
https://gyazo.com/733e96d05ea76bf81846ff1d57b4a069
will do this next

**Comment by miner-bob-1960** [comment]
Amber can Easley be obtained with the Orechid

**Comment by krakel** [comment]
Its needed for Thaumcraft (Mnemonic Matrix, ...)

**Comment by tyler489** [comment]
obtainable with orechid and a new recipy
