### ISSUE TITLE
Tinker Construct can be removed

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#335]
Most of the parts of Tinker Construct are disabled or replaced by other mods.
The higher tiers of tools can not craft. All recipes for casts at the Alchemic Chemistry are hidden by simple cast.
For example:
Axe Cast: Blank Pattern + Iron Axe
Broadaxe Cast: Blank Pattern + Iron Axe + Iron Axe + Iron Axe
The Chemistry Set select the simple recipe and ignore the other.
Most other cast for weapons and other tools does not exists.

OK, all Tinker Parts exist as Xtreme Crafting recipes with Inifiny Ingots. (Hypovolemia Infinity Evolved !!!)

**Comment by tyler489** [comment]
the tier 2 recipys were changed in the comming update

**Comment by SirStudMuffin** [comment]
First off it will not be removed, tinkers construct adds more than just tools
