### ISSUE TITLE
add Remove Soul Corruption as quest reward

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#338]
The evil chicken of the mod Sanguimancy make my crasy! With this tool you can remove the soul corruption. But its Creative Only. It could be part of the last quest Corruption Tools.

**Comment by kindlich** [comment]
There's a ritual that lets you minder your corruption.

**Comment by krakel** [comment]
Ups, and the name is?

**Comment by kindlich** [comment]
Well, generally it's only a block, and it needs some rituals around it... Just check the sanguimancy book for details
