### ISSUE TITLE
Potential Dupe

### ISSUE THREAD

**Issue by Messiah7** [MyM-ModpackTeam/hypovolemia#345]
You can catch Robit from Mekanism in Safari Net, and spawn him with MFR spawner. You can fill Robit inventory with cool stuff, then catch him, then spawn him exact copy - each new Robit will have the same items in the inventory as the original.
That can work with any entity which has inventory and can be caught in Safari Net (Like a Zombie, of course if he take item)

I test in SP with zombie, force him to take cardboardbox with chest, but he nothing take except vanilla stuff, maybe need more tests

**Comment by johnfg12** [comment]
Il disable it next update
