### ISSUE TITLE
Hypovolemia Crash

### ISSUE THREAD

**Issue by AshuraxNinja** [MyM-ModpackTeam/hypovolemia#347]
http://pastebin.com/BJjB3bBh
Apparently dying crashes you, on top of dupes any item that drains a player's health. I.E; Sacrificial dagger.

**Comment by tyler489** [comment]
crash report please not launcher log

**Comment by SirStudMuffin** [comment]
I asking him for the log as, his client didnt crash he got removed from the server as i understand it, I might be wrong though

**Comment by Sandstroem** [comment]
Yes, had that some days ago. Used my bound pick with empty netrwork, it disconnected me from the server. the pick did its thing and I am sure I did not get a duped pick there. But that is not really a new issue.

**Comment by johnfg12** [comment]
as we can not fix this i will close this
