### ISSUE TITLE
Chisel Client Crash

### ISSUE THREAD

**Issue by xXBuilderBXx** [MyM-ModpackTeam/hypovolemia#348]
Chisel causes a client crash when trying to insert or open the chisel GUI with Red Rock i have not tested this with Red Cobblestone or Red Rock Brick. There probably isn't anything you can do to solve this or patch it unless there is a chisel blacklist in the server configs that you can add.

Crashlog: http://pastebin.com/vt0UAWig

**Comment by tyler489** [comment]
Doesn't happen to me.

**Comment by chuggafan** [comment]
It appears someone made an object and didn't initialize it in java in your crash-report, *sigh* goddamnit devs

**Comment by tyler489** [comment]
huh not sure this is on our side... as we dont have anything added to the redrock chisel..

**Comment by tyler489** [comment]
fixed by forcibly adding a exchange on the redrock
