### ISSUE TITLE
Redstone Block no longer craftable due to OreDictionary sand

### ISSUE THREAD

**Issue by Mysteriez974** [MyM-ModpackTeam/hypovolemia#350]
Hello,
I was playing through 0.1.8 when I got to the "God of Jokes" quest and realised that the redstone block was no longer craftable.

A few minutes of searching through scripts later, and it appears that the issue is very simple :
In **src/scripts/AAA_vars_and_oreDicts/AA_vars.zs**, line **244**, we have "sandOredict = <ore:Sand>;".
And the issue is the **uppercase S in Sand**. Replace it with a lowercase one and the recipe works again.

**Comment by kindlich** [comment]
I'll check, wait a sec...

**Comment by kindlich** [comment]
Fixed
