### ISSUE TITLE
Quest detection fails - "Discount" in the Thaumcraft chapter.

### ISSUE THREAD

**Issue by BluCalculator** [MyM-ModpackTeam/hypovolemia#353]
It doesn't detect the sanguine set.
![2016-08-14_12 57 37](https://cloud.githubusercontent.com/assets/3198310/17646991/b8845514-621e-11e6-9331-ccd23760d26b.png)

Sanguine Helmet (ID 5234)
Sanguine Robes (ID 5235)
Sanguine Leggings (ID 5236)
Sanguine Boots (ID 5237)

**Comment by YourMCGeek** [comment]
They detected for me?

**Comment by YourMCGeek** [comment]
Done.

**Comment by johnfg12** [comment]
since mcgeek says the issue is fixed il close this
