### ISSUE TITLE
Crash: crafting Tool Forge

### ISSUE THREAD

**Issue by Alifalafel** [MyM-ModpackTeam/hypovolemia#360]
I went to make a tool forge on the MyM hypovolemia server (using a TiCon slab crafting station), and whenever I'd place the final item in the pattern area, Minecraft would close completely (client side, not server disconnect). Multiple times this happened, as well as when I tried to re-enter that crafting station with the materials already in it from the previous attempts. It happened no matter which piece I placed last. Not sure whether others can duplicate, or what else you guys need to know!

**Comment by bookerthegeek** [comment]
Cords for your base? Place the items you were crafting with in a chest on the table.

**Comment by Alifalafel** [comment]
1973x 1931z.

**Comment by tyler489** [comment]
Crash report

**Comment by Alifalafel** [comment]
[crash-2016-08-18_20.57.41-client.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/427854/crash-2016-08-18_20.57.41-client.txt)
[crash-2016-08-18_20.52.49-client.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/427855/crash-2016-08-18_20.52.49-client.txt)
[crash-2016-08-18_20.47.22-client.txt](https://github.com/MyM-ModpackTeam/hypovolemia/files/427856/crash-2016-08-18_20.47.22-client.txt)

**Comment by johnfg12** [comment]
since tinkers constructs devs no longer support 1.7.10 il close this as there is nothing we can do
