### ISSUE TITLE
Quadrum Redrock

### ISSUE THREAD

**Issue by stijn04356789** [MyM-ModpackTeam/hypovolemia#362]
With the new update it is no longer possible to get redrock as the quadrum redrock doesn't drop it anymore.

**Comment by Sandstroem** [comment]
Does it drop anythign at all? It should drop Extrabiomes (or what the mod is called) Red Cobblestone.

**Comment by stijn04356789** [comment]
It comes from a ticket in our ticket system. The best option is to test it yourself on hypo or by speaking with the player HypoAkatsu on the forum.

**Comment by Sandstroem** [comment]
Ok, can't test it right now. Only this evening. I looked up the commit on github, it should drop Red Cobble since the last update. I suggested this change so that it behaves like vanilla clean stone, where you get cobble when you mine it.

**Comment by kindlich** [comment]
You can get quadrum's redrock via chisel if you decide to use that instead of the ExBio one...

There's a chisel group containint only those two redrocks, so it's still obtainable, even if it doesn't drop anymore...


Long story short:

1. Mine redrock, you get redrock cobble (ExBiomes)
2. Smelt redrock cobble to get redrock (ExBiomens)
3. Use chisel to convert redrock (ExBiomes) to Redrock (Quadrum)

**Comment by krakel** [comment]
I can confirm that. I used the SP version 0.1.8 with the last scrips from Github. The redrock disappear with any tool. (redrock from second level at surface and redrock from the obelisk structure)

**Comment by gusaman** [comment]
I have detected a divergence between the file  config/quadrum/block/redrock.json in  version 0,17  and 0.19 
 0.17 "ExtrabiomesXL:terrain_blocks1", "amount": "1"}
0.19 "ExtrabiomesXL:terrain_blocks1:1", "amount": "1"}

after changing version 0.19 to 0.17 the redrock from Quadrum drops again Red rock from ExBio

**Comment by tyler489** [comment]
Its suppost to drop red cobble which has a data of :1

**Comment by tyler489** [comment]
Cansomeone replace /config/quadrum/block/redrock.json with this
{
    "name": "redrock",
    "default-texture": "redrock",
    "material": "rock",
    "hardness": 1,
    "resistance": 10,
    "type": "block",
    "drops-self": "false",
    "drops": [
        {"item": "ExtrabiomesXL:terrain_blocks1", "damage": "1" "amount": "1"}
    ],
	"flammable": "false",
    "mining-level": 1,
    "requires-tool": "false"
}

And test in SP please

**Comment by gusaman** [comment]
after the replacement of the json file and in SP, 
The Quadrum redrock appears in the bone spires and in all but the first layer in the ground . After brealing it drops red cobbleston. . The first rock layer  is ExtraBiomesXL red rock and drops red cobblestone.

**Comment by tyler489** [comment]
Fixed https://github.com/MyM-ModpackTeam/hypovolemia/commit/db6c41574877da61f2ad23c8be1825b4a095ebbd
