### ISSUE TITLE
recipe altar

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#363]
The altar need bone 352:1. Mincraft produce only bone 352. Can you change the recipe?

**Comment by kindlich** [comment]
Hm...
When I rewrote the recipe I was asked literally
"you can only get the ones with :1", could you make the recipe like that?"...

**Comment by Messiah7** [comment]
Just with bone 352:1 not work shift+Lclick in NEI, but altar still craftable if you put bone manually

**Comment by tyler489** [comment]
Can u change it tk use bone:*

**Comment by chuggafan** [comment]
Break the bone blocks to get the altar stuff
