### ISSUE TITLE
Quest "The simple way" does not give thaumonomicon as reward

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/hypovolemia#364]
The normal way consumes a thaumonomicon and gives you a new one, the simple way does not.

**Comment by Sandstroem** [comment]
Also the rewards are wrong. The simple way should give only 2 nodes, not 10.

**Comment by tyler489** [comment]
Intended as of last update

**Comment by Sandstroem** [comment]
But it doesnt make any sense. First you need to recraft a Thaumonomicon, what's the point in that?

And secondly, why would anyone use the normal way now?
The old choice was between the deconstruction table or more nodes. Now you get more nodes AND the deconstruction table in the simple way. There is no need to choose the normal way any more.

**Comment by chuggafan** [comment]
Simple way gives you the cheat sheet, no?

**Comment by Sandstroem** [comment]
No, that was the cheaty way. That one got removed.
There was a bug that the simple way was changed to a autodetect task, so once you had the Thaumonomicon you couldnt select the normal way anymore. That was fixed in the last update.

The normal way gives 8 nodes, the simple way 2 nodes and the deconstruction thing. Now the normal way gives 2 nodes and the simple way gives 10 nodes and the deconstruction thing. So the normal way is useless, since nobody will ever choose that.

**Comment by chuggafan** [comment]
I would be fine with the previous way the quests were, they seemed more balanced (when there was the trio of quests)

**Comment by Sandstroem** [comment]
Well the cheaty way was removed, since the majority of the team considered it as, well, too cheaty. I think Caithleen had always those people in mind who have done Thaumcraft a million times and know how to handle all that instant warp.

**Comment by YourMCGeek** [comment]
It gives it for me. Done.

**Comment by johnfg12** [comment]
since the issue seems to be resolved according to mcgeek il close this
