### ISSUE TITLE
Mekanism Logistical Sorter Noise

### ISSUE THREAD

**Issue by ZippityDoodah** [MyM-ModpackTeam/hypovolemia#368]
The Mekanism Logistical Sorter clicks constantly, and there is no sound options in the GUI.  According to what I've read on the web regarding this issue, is that there is a setting in the Config files to disable the sound... Is it possible to have this done as there is no Upgrade section in the GUI and this pack has no Muffler block to mute or at least really tone down the noise it makes? And the noise has a good distance to it... If there was another item transport system available I'ld use it, but this pack limits us to Mekanism...

Thanks,

Zip

**Comment by Messiah7** [comment]
You can turn off all mekanism sounds via config file Mekanism.cfg 
Way to find it, run launcher -> right-click on Hypovolemia -> View folder/instance -> config folder -> Mekanism.cfg
Change
B:EnableMachineSounds=true
To
B:EnableMachineSounds=false

Here no other way to disable sorter sounds

**Comment by ZippityDoodah** [comment]
Made the change, restarted the game, but the same thing occurs, no change in sounds from the Logistical Sorter. Is it possible it has to be a server side change in the config, not the client?

Zip

**Comment by johnfg12** [comment]
doesnt seem to be much we can do since that should silence it
