### ISSUE TITLE
Update Elrol's GUI Elevator from 1.5 to 1.6

### ISSUE THREAD

**Issue by Messiah7** [MyM-ModpackTeam/hypovolemia#370]
> -Changed how the Elevator is placed
> -Added advanced Elevators (use a diamond on one)
> -Added a white-list feature to Advanced Elevators
> -Added a camouflage feature to Advanced Elevators
> -Added config options for the permissions to use, and for a black-list of blocks for the Camouflage

**Comment by johnfg12** [comment]
yep this is on our todo list :)
