### ISSUE TITLE
Bloodmagic recipes are not showing up in NEI anymore

### ISSUE THREAD

**Issue by kevingvand** [MyM-ModpackTeam/hypovolemia#372]
Since today's update, the blood magic recipes are not showing up in blood magic. This problem was checked by multiple people. The scripts are still existing and working as far as I have tested.

**Comment by johnfg12** [comment]
@kindlich im leaving this to you as i dont understand those filters at all

**Comment by kindlich** [comment]
Ok, let's see...

I know that there is a client-server synching issue, but I don't know why...
Usually it works if you join the server, then disconnect and re-join.
Could you test that please?

**Comment by Alifalafel** [comment]
Disconnecting/reconnecting seems to work.

**Comment by johnfg12** [comment]
thats a nei bug which we can fix unfortunately
