### ISSUE TITLE
"Did i die? Where am I?" Quest

### ISSUE THREAD

**Issue by Agonys** [MyM-ModpackTeam/hypovolemia#383]
One quest on "Did i die? Where am I?", exactly "Easing life." can't be completed. Even after item crafting quest doesn't detect this item (ultimate fluid tank). Quest doesn't have manual detect.

**Comment by DruidIdrur** [comment]
I'm sorry but this pack has been dropped, and development of it has stopped, your welcome to fix bugs and stuff to continue your gameplay uneffected

**Comment by Elrol** [comment]
I have taken up fixing the issues and bugs, I am working on fixing all the bugs/issues listed on here, I have it forked and I aslo have a discord regarding development of this pack

**Comment by SirStudMuffin** [comment]
Send me the discord link. Also we stopped developement because we all got banned ;)

**Comment by Elrol** [comment]
lol one sec
here it is: https://discord.gg/xeDzngT

**Comment by ghost** [comment]
I didnt get banned, I just moved on to developing my own projects and left
MyM. I would appreciate a discord link to sate my curiosity and hopefully
contribute to bug hunting.

I hope you do it properly, and take full advantage of git to have multiple
branches to manage modpack versions properly.

Another suggestion is to use a testing suite and benchmark performance
every build so you actually see if certain mod additions affect
performance. Cheers.
