### ISSUE TITLE
Possible Mods

### ISSUE THREAD

**Issue by MaelstromPhx** [MyM-ModpackTeam/hypovolemia#49]
Just a list of mods to consider:

Arcane Arteries: http://www.curse.com/mc-mods/minecraft/230977-arcane-arteries
DSU: http://minecraft.curseforge.com/projects/simplelabels
Steve's mods (Personal favorite. Just putting it here so I can say I tried ;D)

more to come

**Comment by drz2k** [comment]
I like the DSU thing. Will make it in i think.
Steves .... well you tried ;)

Arcane Arteries - as i understand that mod, its main use is making early bloodgame faster? We allready do that our own way ... or do i miss something there?

**Comment by drz2k** [comment]
Simple labels is in.
