### ISSUE TITLE
<Bug> <minor> Witcheey wood

### ISSUE THREAD

**Issue by tyler489** [MyM-ModpackTeam/hypovolemia#54]
Witchery wood crafts into planks not wood splinters bypassing progression

**Comment by Bennyboy1695** [comment]
Witchery recipes and the wuestline are still being worked on so will be changed in the next update and hot fixed in the server

**Comment by Bennyboy1695** [comment]
https://github.com/MyM-ModpackTeam/hypovolemia/commit/06e0b32304460f9390018ccd97c033ba7bf6e71a
