### ISSUE TITLE
Dupe bug with the unifier

### ISSUE THREAD

**Issue by chuggafan** [MyM-ModpackTeam/hypovolemia#56]
You put nuggets in while it perfers oreberries, then you get oreberries, get nuggets, oreberry em', rinse, repeat

**Comment by drz2k** [comment]
Good finding. Think we dont need the unifier at all so it will burn :)

**Comment by chuggafan** [comment]
same thing with the oredictionarifier :P

**Comment by drz2k** [comment]
Awaiting more targets!

**Comment by chuggafan** [comment]
forge lexicon Kappa

**Comment by drz2k** [comment]
Dude, i got a full fleet here waiting for targets! More!

**Comment by chuggafan** [comment]
i don't think of any more, the lexicon isn't even in the pack btw XD

**Comment by drz2k** [comment]
Wut? Chugga no more dupes? *disappointed*

**Comment by chuggafan** [comment]
it was a dupe that i was thinking was there since it started, didn't test until now :P

**Comment by drz2k** [comment]
lazy chugga!

**Comment by chuggafan** [comment]
lol, known thing :P

**Comment by drz2k** [comment]
Aaaand they are gone.

**Comment by tyler489** [comment]
why not just remove oredic nugget(orename) from the oreberry
