### ISSUE TITLE
JourneyMap doesn't render blood lakes

### ISSUE THREAD

**Issue by shadowpanther** [MyM-ModpackTeam/hypovolemia#57]
As the title says, the JourneyMap doesn't detect Life Essence fluid blocks and shows the underlying landscape instead.

**Comment by drz2k** [comment]
Mod issue

**Comment by shadowpanther** [comment]
Hmm, I didn't see any updates, but now it renders blood lakes.

**Comment by shadowpanther** [comment]
A quick update - JorneyMap doesn't render blood the first time it starts or after the rendered map is cleared. Subsequent launches seem to render correctly.
