### ISSUE TITLE
Sacrificial Knives

### ISSUE THREAD

**Issue by WinJ9000** [MyM-ModpackTeam/hypovolemia#58]
Whenever you die due to the sacrificial knife, it duplicates them by keeping the knife in the inventory and dropped on the floor

**Comment by drz2k** [comment]
New BM version is on the way, maybe its allready fixed

**Comment by WinJ9000** [comment]
Ahh k

**Comment by tyler489** [comment]
So f this issue is unrelated to having /god can god be reinabled?
