### ISSUE TITLE
Anything that can kill you will duplicate upon death

### ISSUE THREAD

**Issue by WinJ9000** [MyM-ModpackTeam/hypovolemia#62]
When you die with sacrificial knife/Sigil of green grove/etc. you will die and drop those items but will also keep the item in ur inventory so it dupes it

**Comment by drz2k** [comment]
does this also happen in singleplayer?

**Comment by WinJ9000** [comment]
Not sure havent tested

**Comment by shadowpanther** [comment]
Probably the same as #58

**Comment by WinJ9000** [comment]
It half happens in singleplayer, the item stays in death screen but is
removed upon respawn

**Comment by WinJ9000** [comment]
Retested and it sometimes would drop 3 or 4 items

**Comment by tyler489** [comment]
Related 44

**Comment by Bennyboy1695** [comment]
#44

**Comment by tyler489** [comment]
also works with spell crystals...

**Comment by Bennyboy1695** [comment]
There should be no reason for this to happen as we have nothing that's trying to keep your inventory on the server, this may be a visual glitch on your end as I haven't experienced any issues like this while testing

**Comment by shadowpanther** [comment]
Definitely not a visual glitch as I got the second dagger too, and placed it into a chest after. It is still there, after several relogins and restarts.

**Comment by tyler489** [comment]
agreed

**Comment by drz2k** [comment]
Cant reproduce it either.

**Comment by drz2k** [comment]
https://github.com/MyM-ModpackTeam/hypovolemia/commit/b168d5ee99418b80fcbe60e4000a8f8b1b87d985

**Comment by SirWilli** [comment]
I can reproduce this only on the server and it seems to be not related to InvTweaks or MosueTweaks as I can reproduce it after removing both.

**Comment by tyler489** [comment]
its not related to both it has something to do with bloodmagic death call event.

**Comment by drz2k** [comment]
Anyone reported it to BM already?

**Comment by Slind14** [comment]
Same issue has been reported on other packs e.g. infinity.
