### ISSUE TITLE
Minor Bug: Sacrificial Knife Quest 

### ISSUE THREAD

**Issue by WinJ9000** [MyM-ModpackTeam/hypovolemia#63]
(Tested in Singleplayer) The Sacrificial Knife Quest is a 'Detecting Quest' but It actually is a Crafting Quest as I attempted to spawn one in single player and it did not complete the quest

**Comment by Bennyboy1695** [comment]
Most of the quests are manual detect quests meaning there should be a button for you to press if it didnt automatically see the knife

**Comment by drz2k** [comment]
Test please if manual detect works.

**Comment by WinJ9000** [comment]
Already tested did not work (Singleplayer) Yes, I clicked on the manual detect button

**Comment by drz2k** [comment]
It works in my testing perfectly fine with not-cheated-in stuff
