### ISSUE TITLE
NEI recipes for storage drawers are misleading

### ISSUE THREAD

**Issue by shadowpanther** [MyM-ModpackTeam/hypovolemia#64]
NEI shows two recipes for full-depth 2x2 oak storage drawers - with planks and with slabs. Planks recipe is correct, slabs recipe makes half-depth drawer. I think, it's the part that shows oredict recipe (showing different kinds of wood) that is wrong.

The same goes for compact 1x2 oak drawers.

**Comment by tyler489** [comment]
Tes its showing Logwood i think
