### ISSUE TITLE
Lava Clumps Underground

### ISSUE THREAD

**Issue by WinJ9000** [MyM-ModpackTeam/hypovolemia#65]
Is this meant to be here? It feels a bit cheaty that you can just grab alot of lava early game for redstone rather than spending alot of blood

**Comment by Bennyboy1695** [comment]
What y level did you find them at ?

**Comment by WinJ9000** [comment]
At the usual world generated y level about y 20

**Comment by tyler489** [comment]
is this in .13 as i thought the update was suppost to patch that. granted on the server you will find them untill the map resets.

**Comment by WinJ9000** [comment]
Well the map did not reset so the previous world gen is still there with
the lava clumps but let me test in singleplayer when i have time

**Comment by Slind14** [comment]
Yes plesse test with a fresh  on the latest Version.

**Comment by WinJ9000** [comment]
The Lava Clumps are still there with the new update (Tested in Singleplayer)
Also, Theres lava and blood liquid in the pools

**Comment by drz2k** [comment]
CoFH Worldgen has been updated to be more aggressive.
