### ISSUE TITLE
Bug?: Logistics Pipe

### ISSUE THREAD

**Issue by WinJ9000** [MyM-ModpackTeam/hypovolemia#67]
Multiplayer Tested: I placed 2 logistics pipe next to one another and one of them dissapeared when I broke both. Already attempted to relog and searched everywhere

**Comment by Slind14** [comment]
reproducible ?

**Comment by WinJ9000** [comment]
Umm meaning?

**Comment by Slind14** [comment]
If we follow your description will be run into the same bug or is it something that might just have been a one in a thousand case.

**Comment by WinJ9000** [comment]
I have no idea let me retest

**Comment by WinJ9000** [comment]
It was probably a 1/1000 case... I dont know how but I tried it twice and it bugged out then I retested it 10 times and it was fine

**Comment by Slind14** [comment]
ok thanks for testing.
