### ISSUE TITLE
Chets recipe overlaps with MC

### ISSUE THREAD

**Issue by drz2k** [MyM-ModpackTeam/hypovolemia#70]

**Comment by ChetwyndKid** [comment]
You know if you make an issue, You need some kind off description. I have no idea what your talking about.

**Comment by drz2k** [comment]
As always. Not helpfull. Recipe has been overwritten. I wish i just deleted that questline. It made more issues now afterwards than i could have produced.

**Comment by drz2k** [comment]
Benny fixed it .. and other stuff :)
