### ISSUE TITLE
iron wand not detected

### ISSUE THREAD

**Issue by tyler489** [MyM-ModpackTeam/hypovolemia#71]
quest dont detect iron wand i know its known

**Comment by ChetwyndKid** [comment]
Thank you for explaining the issue, It helps quite a bit when people do that.

**Comment by Bennyboy1695** [comment]
Fixed already in Commit https://github.com/MyM-ModpackTeam/hypovolemia/commit/8815b57df3bdc8dbb85a7987a801a5c2791c0f8d

**Comment by tyler489** [comment]
#70
