### ISSUE TITLE
The blank casts are 2 different metas

### ISSUE THREAD

**Issue by chuggafan** [MyM-ModpackTeam/hypovolemia#73]
You can't make anything with the craftable blank casts due to the fact that they have 2 completely different metadatas

**Comment by drz2k** [comment]
Please change this file and retry.

**Comment by Slind14** [comment]
ref is not clickable due to missing text, use this one:
https://github.com/MyM-ModpackTeam/hypovolemia/commit/4667d91cece1a5849b202bd9b996496cf0ba171c
