### ISSUE TITLE
Placing Existence Burners kicks the player with "Internal server error"

### ISSUE THREAD

**Issue by Ferrettomato** [MyM-ModpackTeam/hypovolemia#77]
When I tried to place an Existence Burner (from Technomancy), I was disconnected with the message "Internal server error". When I logged back in, the burner had been placed, but it was still in my inventory. I *have* seen it absorb enemies.

**Comment by drz2k** [comment]
From my testing the whole essence burner thingy seems unfinished. I might just remove them until they get a real use.

**Comment by NanoFlame** [comment]
All items from the existence mod that are placed do that and kicks you and dupes the item.

**Comment by drz2k** [comment]
Is this only happening on the server or also single?
