### ISSUE TITLE
Soul Armor Forge quest gives activation crystals as a reward; is this a bug?

### ISSUE THREAD

**Issue by Ferrettomato** [MyM-ModpackTeam/hypovolemia#78]
Weak Activation Crystals make no sense as the reward for this quest, much less four of them. My guess is that they were SUPPOSED to be Master Blood Orbs, considering the similar item IDs and the comparative usefulness of having four of the same item for bound armor.

**Comment by tyler489** [comment]
Almost  certain its intended as i reported that the crystals had been bound to caithleen here..

**Comment by chuggafan** [comment]
you don't even need a crystal to activate the forge, lol
