### ISSUE TITLE
Quest Bug: Retirement of the bucket

### ISSUE THREAD

**Issue by LucidTheStick** [MyM-ModpackTeam/hypovolemia#79]
My questbook won't detect the electric pump for the 'Retirement of the bucket' quest. Yes, I've clicked manual detect.

Reported by Win_9000 on MyM Tickets

**Comment by shadowpanther** [comment]
#59, and it was supposed to be fixed (worked for me after the fix)

**Comment by LucidTheStick** [comment]
Ticket was reported... 4 days ago on.  Could be fixed but wanted to open this before I closed our ticket so it wasn't lost =)

**Comment by shadowpanther** [comment]
Win_9000 reported it at least twice here (#68, #69)

**Comment by drz2k** [comment]
We're still in alpha. If someone reports to the forums about modpack issues, redirct them to the git. MyM forums should only be used for community/server specific issues. When i give someone access, i clearly point them here for reporting.

**Comment by LucidTheStick** [comment]
Thanks for the berating for trying to pass on a player issue.  I couldn't find the information being posted here when we advised the player to in the ticket with no update back from them.  I will close the tickets in the future without trying to help you guys.
