### ISSUE TITLE
fisher missing recipy required for quest

### ISSUE THREAD

**Issue by tyler489** [MyM-ModpackTeam/hypovolemia#80]
im guessing this is one of those things that caithleen changed his/her mind about disabling and make it a quest anyway... anyway heres a recipy

**Comment by tyler489** [comment]
hm it wont let me post it ... it edits out the brackets
ill send it to you on the forums

**Comment by tyler489** [comment]
recipes.addShaped(<MineFactoryReloaded:machine.0:1>, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<minecraft:fishing_rod>, <MineFactoryReloaded:fishingrod>, <minecraft:fishing_rod>], [<ore:sheetPlastic>, <MineFactoryReloaded:machineblock>, <ore:sheetPlastic>]]);

**Comment by Slind14** [comment]
@tyler489 you can do it like this:
```
recipes.addShaped(MineFactoryReloaded:machine.0:1, [[ore:sheetPlastic, ore:sheetPlastic, ore:sheetPlastic], [minecraft:fishing_rod, MineFactoryReloaded:fishingrod, minecraft:fishing_rod], [ore:sheetPlastic, MineFactoryReloaded:machineblock, ore:sheetPlastic]]);
```
raw: http://pastebin.com/Z7vgCf8X

**Comment by tyler489** [comment]
ah thanks slind
http://pastebin.com/wQBkSBqh

**Comment by tyler489** [comment]
also yours is missing the <> slind

**Comment by drz2k** [comment]
Humm its a bug in fact ...

Fisher {
        # The energy cost for this machine to complete one work cycle, in units of 10 RF (i.e., 2 DaRF = 20 RF)
        I:ActivationCostDaRF=2
        B:Recipe.Enabled=true
    }

**Comment by drz2k** [comment]
Fixed

**Comment by Slind14** [comment]
@tyler489 I copied yours. What I meant is to post it like it is on pastebin on here, so it doesn't remove the brackets. With the ` 3 times at the beginning and end.

**Comment by tyler489** [comment]
'''<code test>'''

**Comment by tyler489** [comment]
'''Code test <><>'''

**Comment by tyler489** [comment]
Still broken on the server.

**Comment by tyler489** [comment]
fixed in Alpha .15
