### ISSUE TITLE
Botania functional flora quests completed prematurely

### ISSUE THREAD

**Issue by Ferrettomato** [MyM-ModpackTeam/hypovolemia#81]
Some time after completing the Botania rune quest, I noticed that every single quest in the functional flora cluster had been completed, even though I had never made any of the requirements before.

**Comment by tyler489** [comment]
change to nbt indepedent not fuzzy.

**Comment by drz2k** [comment]
Cant be fixed, the quests must be changed.

**Comment by drz2k** [comment]
@NanoFlame you're fixing this or do i need to?
