### ISSUE TITLE
Gold wand uncraftible

### ISSUE THREAD

**Issue by tyler489** [MyM-ModpackTeam/hypovolemia#82]
it requres a wand mold but that itself is not yet craftible.

**Comment by tyler489** [comment]
edit neither does the greatwood wand core

**Comment by drz2k** [comment]
http://imgur.com/a/0Ua1a Humm ?

**Comment by tyler489** [comment]
howed u get the mold

**Comment by drz2k** [comment]
Just use vanilla TC ...
