### ISSUE TITLE
essence quest failed to compleate

### ISSUE THREAD

**Issue by tyler489** [MyM-ModpackTeam/hypovolemia#83]
for some reason the tanks wont detect correctly.. in the second chance questline can you turn it back to 5mill millibuckets through the qds if you make it fuzzy or nbt independent it will detect to early

**Comment by drz2k** [comment]
which quest exactly? *sigh*

**Comment by tyler489** [comment]
its called ESSENCE in the SECOND CHANCE questline

**Comment by drz2k** [comment]
Cant reproduce this, retest with upcoming build.

**Comment by tyler489** [comment]
still unable to do it
bound to qds tossed 10 tanks full of mobessence in the qds and nothing updates.

**Comment by drz2k** [comment]
https://youtu.be/sAi4tprSd2g could someone else copy the issue?

**Comment by TheLogan** [comment]
I just tried it. with a tank I've had in use for some time, and that I just filled with monster essence from a grinder, it just vanished.
However, a tank that I cheated into existence, was accepted, I'm not sure what the difference could be, but I'll test a little more

**Comment by TheLogan** [comment]
OK. I just cheated a full tank of monster essence in, then an empty tank, then I placed the full one on top of the empty one and poured everything into the empty one which now had 14000mB monster essence, then I submitted it to the QDS, it was not accepted.
So whatever the case may be, it seems like anything but a cheated in essence tank is not accepted.

**Comment by drz2k** [comment]
I have a lot of tanks to fill -.-

**Comment by shadowpanther** [comment]
I can confirm that in MP, portable tank filled with Essence the normal way (Grinder and such) and submitted through QDS won't count to this quest's progress.
