### ISSUE TITLE
uh i found a bypass

### ISSUE THREAD

**Issue by tyler489** [MyM-ModpackTeam/hypovolemia#84]
Found a way to plant anything without cropsticks
![2015-10-23_10 26 51](https://cloud.githubusercontent.com/assets/7015040/10697426/7c03a130-7971-11e5-86cb-0fc945c72d6f.png)

**Comment by drz2k** [comment]
and could you explain it maybe? *sigh*

**Comment by tyler489** [comment]
aww but i dont want to
you might remove it...

seed bag

**Comment by drz2k** [comment]
you are right, but not with the "might" :P

**Comment by tyler489** [comment]
ok youll have to make a new recipy for ordo shards then ;(

**Comment by tyler489** [comment]
now how am i going to magic fertilize all my crops...
