### ISSUE TITLE
[suggestion] more power sources

### ISSUE THREAD

**Issue by chuggafan** [MyM-ModpackTeam/hypovolemia#85]
The amount of blood dynamos and time it takes to make charged draconium blocks is so insane it gets ridiculous, please, add more ways to get power that don't take forever

**Comment by drz2k** [comment]
More power generation is on its way ;)

**Comment by drz2k** [comment]
50% done (DE fusion)

**Comment by johnfg12** [comment]
@drz2k how far did you get on this?

**Comment by drz2k** [comment]
ask @Matryoshika :D

**Comment by SirStudMuffin** [comment]
Added new power gens

**Comment by chuggafan** [comment]
Better not be ExU generators, we wanted endgame power sources, not early game, just an FYI

**Comment by SirStudMuffin** [comment]
Can this be closed!

**Comment by GGothicRide** [comment]
Immersive Engineering has been added to help with power gen for now, if it needs more please feel to submit another issue ticket
