### ISSUE TITLE
Tank vanishing when pickaxe breaks

### ISSUE THREAD

**Issue by TheLogan** [MyM-ModpackTeam/hypovolemia#86]
When using a wood or stone pickaxe on a mekanism tank, if the pickaxe breaks (is on it's last durability) the tank will not spawn an item but will instead vanish.

**Comment by TheLogan** [comment]
It struck me that it might be a mekanism bug, and it seems the same goes for other mekanism machines

**Comment by TheLogan** [comment]
The same goes for iron pickaxe.
I have yet to test it on tinkers' tools though.

**Comment by drz2k** [comment]
As all mekanism issues that arent beeing fixed, this is on the known issuel ist now.
