### ISSUE TITLE
Two seed-related crashed

### ISSUE THREAD

**Issue by shadowpanther** [MyM-ModpackTeam/hypovolemia#88]
I'm trying to automate my seed analyzer. These are the crashes I've encountered. Building the system doesn't cause the crash, but when the system tries to move any seed, the crash happens.

chest->mekanism logistical transporter->seed analyzer => server crash
seed analyzer->translocator->seed storage => client crash

**Comment by tyler489** [comment]
i thought seed storages were buggy... aka nyi.
also crash report.

**Comment by shadowpanther** [comment]
Sorry, not client _crash_ but a disconnect in the second case. Logs for both cases are server-side, I suppose.

**Comment by drz2k** [comment]
I fear we wont get any fixes from mekanism soon, will put this into a known issue list
