### ISSUE TITLE
Can't get coven witches for witchery

### ISSUE THREAD

**Issue by chuggafan** [MyM-ModpackTeam/hypovolemia#89]
You cannot get coven witches to do a lot of witchery rites, i would love to be able to get them, thanks

**Comment by Bennyboy1695** [comment]
being worked on

**Comment by chuggafan** [comment]
thank you, we need 6 of them at least per person who wants to do witchery (and have them indefinitely available if we want to try to taglock ourselves in case we kill one)

**Comment by chuggafan** [comment]
Copypasta from the accidental duplicate of this:
It is STILL not possible to get all the coven witches from witchery, as you have to claim the villager egg from EVERY quest and the coven witch egg from EVERY quest, if you don't, you can't possibly get enough, also, if you slept in a bed, good luck, because now you've got to make sure you don't accidentally kill the coven witches, we really need an infinite way to get them, maybe a repeatable quest or something, as to make them infinite
