### ISSUE TITLE
if you look up portable tank in NEI game crashes

### ISSUE THREAD

**Issue by DarthWesix** [MyM-ModpackTeam/hypovolemia#90]

**Comment by tyler489** [comment]
Go to nei subsets go to mekanismm andm right click  the tank so it turns darkgray.. its a mod issue as it happens on ferrit buisness as well.

**Comment by Slind14** [comment]
Please post the crash report on gist.github.com and link it here

**Comment by DarthWesix** [comment]
http://pastebin.com/qBV2H8kT like this?

**Comment by Slind14** [comment]
http://wiki.mym.li/en/latest/Knowledge_Base/crashreport.html

**Comment by DarthWesix** [comment]
https://gist.github.com/DarthWesix/bd65a2dbbecbcfb1b67b

**Comment by Slind14** [comment]
thank you. You will need to assign more memory to the pack in case you have 64 bit and some free up. If not remove the texture pack, in case you have one. The crash is not related to the initial issue report.

**Comment by shadowpanther** [comment]
http://pastebin.com/1Q1vHcqS
Using NEI to look for usage of Mellifluous Hunger crashes the client.

**Comment by Sandstroem** [comment]
I have a similar issue with the portable tank. Minecraft doesnt response for like half a minute or so. Then i can continue.

It freezes after I have typed "po", and there seem to be 11 pages of stuff starting with "po".

**Comment by tyler489** [comment]
Portable Tank....

**Comment by drz2k** [comment]
Should be fixed in current, else reopen pls.
