### ISSUE TITLE
Tooltips for mekanism factories are broken

### ISSUE THREAD

**Issue by TheLogan** [MyM-ModpackTeam/hypovolemia#91]
All tooltips for the mekanism factories are substituted with
tooltip.Factory

**Comment by drz2k** [comment]
Probably mod issue (or in combination with another mod).

Sadly Aidan isnt really fixing stuff v7 anymore while he works on v8.

**Comment by drz2k** [comment]
Mekanism isnt fixing stuff atm - put it on the known issue list.
