### ISSUE TITLE
Broken Witchery Recipe

### ISSUE THREAD

**Issue by Slind14** [MyM-ModpackTeam/hypovolemia#92]
Alpha0.16
```
ERROR: witchery.zs:35: Could not resolve <witchery : embermoss , < witchery : ingredient : 21>
```

**Comment by Bennyboy1695** [comment]
Fixed in 1cafd57aea37354c9739e7cc9d5853e869136eab

**Comment by Slind14** [comment]
did you load up, to make sure there isn't any other after this line?

**Comment by Bennyboy1695** [comment]
i had already fixed it seconds after pushing the original just forgot to push the fixed version

**Comment by Slind14** [comment]
alright, thanks
