### ISSUE TITLE
Things left in altar when exiting game may act weird

### ISSUE THREAD

**Issue by TheLogan** [MyM-ModpackTeam/hypovolemia#94]
I think this is mainly for SP since servers don't usually close down, but I've noticed something weird happening with things I've left in the blood altar when closing the game down.
As an example I left my apprentice blood orb in there last night, and this morning it was gone.
This morning I spawned in a new apprentice blood orb, registered it and put it in the altar where it worked away happily. Then I logged out and back in, everything was fine, I did this a few times and on the third go the orb was there but it wasn't sucking up lifeforce any more, so I picked it up and it had unregistered itself.

I've lost things before but didn't really notice it, a stack of planks here, a few cobblestones there, I thought that perhaps I'd just forgotten where I put them. But my apprentice orb was placed there for a specific reason and hadn't been moved before it vanished, which was when I became suspicious.

**Comment by tyler489** [comment]
mod bug i think.

**Comment by TheLogan** [comment]
Not unlikely, but a bug non the less, so thought I'd just post it anyway =)

**Comment by drz2k** [comment]
We are on a current dev build of bloodmagic.

Anyone volunteering to test this with latest release ? 

http://www.curse.com/mc-mods/minecraft/224791-blood-magic#

**Comment by drz2k** [comment]
https://github.com/MyM-ModpackTeam/hypovolemia/commit/b168d5ee99418b80fcbe60e4000a8f8b1b87d985

**Comment by drz2k** [comment]
Pending to closure T-3
