### ISSUE TITLE
Sheep essence wool acts weird

### ISSUE THREAD

**Issue by TheLogan** [MyM-ModpackTeam/hypovolemia#96]
I've used a few of different magical crop essences so far and they've all been fine. Sheep essence however is acting weird.

What I did:
I grabbed 27 units of sheep essence, enough for 3 blocks of wool.
I put them out in a 3x3 in a standard crafting table window.
Then I shift clicked the output slot to place all possible (3) into my inventory, this didn't do anything.
I then shift clicked to pick up all and I got 1 wool block and 1 sheep essence was removed from each stack in the crafting field.
I then just left clicked and placed them in my inventory manually.
Which was when things started getting really funky..
The moment I placed one on top of the other one of them vanished and left me a stack of 1

I then placed the last one in a field next to the first one and clicked "r" to sort my inventory, which resulted in the last one vanishing. So in the end I'm left with 3 block of wool instead of 3, and I don't trust that last block as it's eaten 2 other blocks already xD

I have however tried taking strings from fallen spiders and used that to create wool blocks just fine, it's only the sheep essence that's bugging.

**Comment by drz2k** [comment]
Seems this is a problem in magic crops. I have reproduced it on a client with only the MC mod and it ate all my wool.
