### ISSUE TITLE
Storing energy tasks completed before they should

### ISSUE THREAD

**Issue by TheLogan** [MyM-ModpackTeam/hypovolemia#98]
The quest "Storing Energy" consists of 4 different tasks, creating one energy cube after the other

Basic
Advanced
Elite, and then
Ultimate

I just unlocked it, and saw only the basic (as I should)
Then I crafted the basic cube, and it had unlocked all other steps and showed them as completed (as it should not have done, since I only had the basic cube).

**Comment by tyler489** [comment]
nbt independent not fuzzy please...

**Comment by TheLogan** [comment]
I'm not sure what that means, if it was meant for me =)

**Comment by tyler489** [comment]
ment for the mod pack makers..

**Comment by TheLogan** [comment]
Goodie! =P

**Comment by tyler489** [comment]
#140
