### ISSUE TITLE
Skeleton seed recipe not working

### ISSUE THREAD

**Issue by TheLogan** [MyM-ModpackTeam/hypovolemia#99]
I'm trying to make skeleton seeds following the NEI recipe here:
http://prntscr.com/8vvbyj

This is my crafting table
http://prntscr.com/8vvbrz

As you can see I'm doing exactly as I'm supposed to, but it's not working.
My suspicion is that it may be because my bones are numbered id 352:1 while the recipe calls for plain 352, I'm thinking this may have something to do with the bones coming from bone pillars rather than from skeletons..?

**Comment by TheLogan** [comment]
I just tried with bones specifically from skeletons, and the recipe accepts them, so it's because bone pillar bones aren't "real" bones =P

**Comment by chuggafan** [comment]
the bone pillar bones aren't the same metadata as the normal skeleton ones, so can someone change the recipie to be fuzzy recipie or whatever? thats the root source of the problem

**Comment by TheLogan** [comment]
I don't know if this is related or should be its own issue, but I just tried making the order shard

1x accio essence
2x bone
2x iron ingot

And just for the heck of it I decided to use the pillar bones, and this recipe doesn't accept pillar bones either
